### PR TITLE
Feedback vertical alignment

### LINKED ISSUE #939: feedback responsiveness
### Description

the form margin top so it is under the header 
the textarea doesn't have a fixed size 

### Steps to reproduce

go to the feedback page

### Screenshots

Screenshot_20230724_013510
Screenshot_20230724_014122

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #939 
I fixed the alignment of feedback page and also setup the char limit for its inputs.

### CODE REVIEW

**Comment by narayan954** [comment]
also, can you disable the resize option for this textarea, so user can't alter as well?

**Comment by Palakkgoyal** [comment]
Removed the marginTop as after merging the relativeRoutes PR there is no need to add margin. You can consider this issue for feedback charLimit.

**Comment by Palakkgoyal** [comment]
Done

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
