### PR TITLE
issue #262 Added Password Hide and Show option

### PR DESCRIPTION
**Pull request by sayedulkrm**
All codes remain the same. I just added Hide and show function.

### CODE REVIEW

**Review by sayedulkrm — COMMENTED** [review]
Thank you

**Comment by narayan954** [comment]
> Thank you

Hi @sayedulkrm,
There's a bug in signup page where we're getting default show button as well. Can you please fix that?
image

It disappears after we have interacted with buttons but appears every first interaction, which is not good.
Please try to fix that.
Thank you.

**Comment by narayan954** [comment]
Please don't comment the code here, I can see the code at files changed section or my local setup.
To regenerate the issue I am facing, go directly from log in to sign up and start typing some characters in the password box, you should be able to notice the issue. 
I'll look and review the code again as well.
Thank you :)

**Comment by narayan954** [comment]
https://github.com/narayan954/dummygram/assets/77617189/e8acb788-ac20-4fc6-90c5-32c02203ba25

**Comment by narayan954** [comment]
could it be browser specific?
let's check that

**Review by narayan954 — APPROVED** [review]
Looks good to me!

**Comment by narayan954** [comment]
Merging it keeping the issue to be handled in mind.
Thanks a lot for your contribution @sayedulkrm

**Comment by sayedulkrm** [comment]
Sorry that I post the code here.
Thank You so much for accepting. 👍🏻 👍🏻

**Comment by narayan954** [comment]
> Sorry that I post the code here. Thank You so much for accepting. 👍🏻 👍🏻

It's okay, keep it up!

**Pull request merged**
