### PR TITLE
Closes #235 [`README`]

### LINKED ISSUE #235: [DOCS] Add Testing info in readme
### Description

We can add Information about cypress and setting up testing environment for the latest addition of test cases in the project.
Also we can add info about adding more test cases and provide reference document for the same in case someone wants to test the project.

### Screenshots

_No response_

### Additional information

This could get big, so include only the necessary info in readme and separate more info in separate markdown

### PR DESCRIPTION
**Pull request by sarkartanmay393**
image

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
> ## Testing
> Here we will see, how to run tests and how to setup new test cases. _We will be using Cypress for our testing purposes._
> 
> ### Introduction to Cypress
> Cypress is a relatively new automated tests tool which is gaining popularity at a very rapid pace
> 
> Here is the home page for Cypress if someone wants to look it up https://www.cypress.io/
> 
> Cypress has very strong documentation so a new comer could find most of the information from their own site https://docs.cypress.io/guides/overview/why-cypress.html#In-a-nutshell
> 
> Also as a starting point it would be good to go through these tutorial videos https://docs.cypress.io/examples/tutorials
> 
> 
> 
> ### Start Testing
> > You need to [setup](#project-setup) the project as usual, and after that we can run our test cases.
> 
> 1. **Run This Command**
> 
> ```shell
> npm run cypress:open
> ```
> 
> _It will open up this window,_
> 
> 
> 
> > As you can see, we only added E2E testing
> 
> 2. **Click on E2E Testing & Select Browser**
> 
> 
> 
> 3. **Now Click on any Test to Run it**
> 
> 
> 
> * **See It Running**
> 
> ### Create New Test Cases
> Working Directory: `/cypress/` E2E Files: `/cypress/e2e/`
> 
> **To Create New E2E Tests**
> 
> 1. Goto `/cypress/e2e/`
> 2. You can create new file (similar to `spec.cy.js`). 
>    **OR** add new `it` function inside existing `describe` function in this existing file.
> 
> test-file-screenshot
> 
> 3. Then, [test](#Start-Testing) your test cases:
>    ```shell
>    npm run cypress:open
>    ```

@narayan954 Hey, it's done ✅

**Review by narayan954 — COMMENTED** [review]
Looks great but as I suspected, this markdown section is quite big now and there might be users not interested in looking at the testing part of the doc, one workaround I can think of is using the details tag `<details></details>`. What's your opinion on this

**Comment by sarkartanmay393** [comment]
@narayan954 I'm adding that too, see it now.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks a lot for your contribution @sarkartanmay393 :)

**Pull request merged**
