### PR TITLE
#444-seperate navbar component

### LINKED ISSUE #444: [FEATURE]Seperate component for navbar/header
### Description

So the idea is to create a separate component for navbar/header so that app.js doesn't  look messy.
scrnli_07_06_2023_13-32-14

Pls assign this to me under gssoc23

### PR DESCRIPTION
**Pull request by Soulpurr**
@narayan954  i have created a separate navbar component.
Kindly verify and approve this.
fixes #444

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by Soulpurr** [comment]
Hey @narayan954 you haven't added any labels in this pr that's why it's not yet counted in leaderboard 🥲

**Comment by narayan954** [comment]
> Hey @narayan954 you haven't added any labels in this pr that's why it's not yet counted in leaderboard smiling_face_with_tear

Right!, I'm really sorry for missing that. I'll go through the pull request timeline as well

**Comment by Soulpurr** [comment]
> > Hey @narayan954 you haven't added any labels in this pr that's why it's not yet counted in leaderboard smiling_face_with_tear
> 
> Right!, I'm really sorry for missing that. I'll go through the pull request timeline as well

Will it be possible to make this pr count in leaderboard

**Comment by narayan954** [comment]
> > > Hey @narayan954 you haven't added any labels in this pr that's why it's not yet counted in leaderboard smiling_face_with_tear
> > 
> > 
> > Right!, I'm really sorry for missing that. I'll go through the pull request timeline as well
> 
> Will it be possible to make this pr count in leaderboard

It should get automatically updated in the leaderboard don't worry :) . Leaderboard refreshes in fixed intervals as it's a CRON Job.

**Pull request merged**
