### PR TITLE
#445-favourite section

### LINKED ISSUE #445: [FEATURE] A separate section for favaorite posts.
### Description

Currently we have no separate section for accessing favourite post we have to open profile section.
I think it will be better if we add a page for favorite post.

pls assign this to me under gssoc23

### PR DESCRIPTION
**Pull request by Soulpurr**
So i have added a separate favourite post section.
Right now in order to navigate favourite section its link is located at the profile bar  which is fine as of now and for mobile devices.
But after merging #437 we can directly navigate from sidebar for larger screens.
You just need to add a link to this page in sidebar favourite item.
fixes #445 
[scrnli_08_06_2023_13-33-16.webm](https://github.com/narayan954/dummygram/assets/92094765/c176ba65-8086-4494-905a-bdffc1b1d7ec)

### CODE REVIEW

**Comment by Soulpurr** [comment]
Hey @narayan954 do verify this

**Comment by narayan954** [comment]
> Hey @narayan954 do verify this

Yes, sure allow me some time.

**Comment by narayan954** [comment]
@Soulpurr , can you please match it against the current implementation and adapt?

**Comment by Soulpurr** [comment]
> @Soulpurr , can you please match it against the current implementation and adapt/improve it?

The sidebar one right?

**Comment by narayan954** [comment]
> > @Soulpurr , can you please match it against the current implementation and adapt/improve it?
> 
> The sidebar one right?

yes

**Comment by Soulpurr** [comment]
> > > @Soulpurr , can you please match it against the current implementation and adapt/improve it?
> > 
> > 
> > The sidebar one right?
> 
> yes

hii @narayan954  i have updated this according to #437 as it doesn't have fav section for smaller screen i have added it so pls verify and approve it.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
