### PR TITLE
Added landing page

### PR DESCRIPTION
**Pull request by AK-shat-JAIN**
#206 issue resolved 
I have created this design and animation 
image
image
image

after this animation, this automatically redirects to the index page from where the user can continue using the website
Please review it and update me If required any more updates or changes

If possible please consider it under hard tag : )

### CODE REVIEW

**Comment by AK-shat-JAIN** [comment]
Hello @narayan954 
Please help me how to deal with these issues

**Comment by narayan954** [comment]
> Hello @narayan954 Please help me how to deal with these issues

what issue?

**Comment by narayan954** [comment]
Hi @AK-shat-JAIN , instead of a separate html file, can you create this animation as a component, that renders for some seconds and then the main app loads. It can be added in between the index.js and app.js. As this is a single page react application, so a separate page doesn't make much sense and components are preferred more.

**Comment by narayan954** [comment]
Also, please remove that white border.

**Comment by AK-shat-JAIN** [comment]
Hlo @narayan954 Sr 
I have very less experience with React components 
That's why I have created This as a separate HTML file 

The white border I added as It looks nice, now as you said I will remove it and push changes

**Comment by AK-shat-JAIN** [comment]
https://user-images.githubusercontent.com/84455686/221418899-01887d69-5b55-4851-80e5-6c34ca808eaa.mp4



That's how it looks...

**Comment by narayan954** [comment]
> 
> https://user-images.githubusercontent.com/84455686/221418899-01887d69-5b55-4851-80e5-6c34ca808eaa.mp4
> 
> 
> 
> That's how it looks...

that's not how react applications are deployed, it'll need to be explicitly configured to be deployed like this. Instead a component is preferable which shall be taken care of by react in production as well.

**Comment by narayan954** [comment]
I can take care of the component aspect ,but you should know as well as components are the basics of react.

**Comment by narayan954** [comment]
> I can take care of the component aspect ,but you should know as well as components are the basics of react. Also, I'll have to increase the difficulty to medium if I do that part.

**Comment by AK-shat-JAIN** [comment]
ok Sr,
I am sorry if any trouble cause due to me

**Comment by narayan954** [comment]
> ok Sr, I am sorry if any trouble cause due to me

it's okay, you can push the change(remove white border) so I can do my part

**Comment by AK-shat-JAIN** [comment]
Ok sr I do that within an hour

**Comment by AK-shat-JAIN** [comment]
done sr

**Comment by AK-shat-JAIN** [comment]
Hello Sr @narayan954 is there any more change I can do?

**Comment by narayan954** [comment]
> Hello Sr @narayan954 is there any more change I can do?

I'll look into it and confirm

**Comment by AK-shat-JAIN** [comment]
ok @narayan954

**Comment by narayan954** [comment]
Hi @AK-shat-JAIN , I made the animation as a component, now can you fix the css styles for it to be compatible with our page. Else, I think we might have to use iframe instead to load the animation properly

**Comment by AK-shat-JAIN** [comment]
Hii @narayan954 ,
I will surely try for the same and update you 👍

**Comment by AK-shat-JAIN** [comment]
Hey @narayan954 
Please have a look I have linked that with an already created landing.css file

**Comment by AK-shat-JAIN** [comment]
@narayan954 Sr 
Please update about it

**Comment by narayan954** [comment]
> @narayan954 Sr Please update about it

Hi, I have my college exams going on that's why I'm less available for one more day. Sorry for the inconvenience, but can you check if the animation intended is working correctly or not on your side as well. It's not working as intended for the changes you've provided. I believe some of the css properties are being overwritten and they need to be configured somehow to make the animation as it was intended to. Index.css styles are overwriting the styles, so you can write the necessary css in index.css only. Landing.css doesn't have much priority so it's better to be left that way I changed it.
As a final resort we might've to go with the current animation, but that's not what we intend to do, right?

**Review by narayan954 — CHANGES_REQUESTED** [review]
similar css exists in landing.css as well as index.css, and one of them is unnecessary. I'd suggest you try to make the css of landing.css work so I can give a finishing touch to this issue

**Comment by AK-shat-JAIN** [comment]
@narayan954 I tried out to delete copy of CSS from index.css which is already present in landing.css

**Comment by narayan954** [comment]
> @narayan954 I tried out to delete copy of CSS from index.css which is already present in landing.css

but that doesn't solves the issue, that's just extra and not what I meant.

**Comment by AK-shat-JAIN** [comment]
> > @narayan954 I tried out to delete copy of CSS from index.css which is already present in landing.css
> 
> but that doesn't solves the issue, that's just extra and not what I meant.

@narayan954 then how to do that 
Sry Buddy, I am not getting it 😥

**Comment by narayan954** [comment]
> > > @narayan954 I tried out to delete copy of CSS from index.css which is already present in landing.css
> > 
> > 
> > but that doesn't solves the issue, that's just extra and not what I meant.
> 
> @narayan954 then how to do that Sry Buddy, I am not getting it disappointed_relieved

try an image instead of svg

**Comment by AK-shat-JAIN** [comment]
I can try to do it with image

**Comment by AK-shat-JAIN** [comment]
Hey @narayan954 
replaced svg with its image

**Comment by narayan954** [comment]
> Hey @narayan954 replaced svg with its image

HI there, svg was better than this image but that's ok... and I'll fix it to my requirements now :)

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by narayan954** [comment]
thanks for your contribution! :)

**Comment by AK-shat-JAIN** [comment]
Thanks Sr greatfull of this

**Pull request merged**
