### PR TITLE
Improve the login page

### PR DESCRIPTION
**Pull request by Walexz01**
# Description

remove the nav from the login and signup page.
create a responsive login page

Solves the issue #623 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

Screenshot_20230703_045808

localhost_3000_dummygram_login

### CODE REVIEW

**Comment by narayan954** [comment]
Hi, I'm reviewing in chronological order :) allow me some time

**Comment by narayan954** [comment]
Hi @Walexz01  it's looking really cool! 
But it's perhaps too big for the screen even at 100 percent scale as you can see in the images below of edge and firefox
microsoft edge
firefox

Can you please use heights as viewport heights so we don't have to scroll.
Also, in mobile screens, some part is beyond screen to the right as you can see.
image
Thank you!

**Comment by Walexz01** [comment]
Ok sir will do that

**Comment by narayan954** [comment]
> Ok sir will do that

You did a great job! Also, don't forget to git pull the changes I've made on your repo

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution @Walexz01 :)

**Comment by Walexz01** [comment]
Thanks @narayan954 
Really Happy to contribute sir ❤️

**Pull request merged**
