### PR TITLE
improve sign up page ui

### PR DESCRIPTION
**Pull request by Walexz01**
#642 

improve sign up page ui

@narayansoni
 
Beforre
Screenshot_20230706_102322

After

Screenshot_20230706_122312

### CODE REVIEW

**Comment by narayan954** [comment]
> #642
> 
> improve sign up page ui
> 
> @narayansoni
> 
> Beforre Screenshot_20230706_102322
> 
> After
> 
> Screenshot_20230706_122312

Hi @Walexz01 can you check the signup page, it's not right at all, also the images etc are  stretching way too much
image

**Review by narayan954 — CHANGES_REQUESTED** [review]
fix the ui error

**Comment by Walexz01** [comment]
Ok sir will check it now

**Comment by Walexz01** [comment]
@narayan954  done sir 
Screenshot_20230706_122312

**Comment by narayan954** [comment]
> @narayan954 done sir
> 
> Screenshot_20230706_105755

hello @Walexz01 , do make this to fit in the viewport, there shouldn't be any need to scroll in normal viewport(without any zoom effects)

**Comment by narayan954** [comment]
you can let the signup form be scrollable but the image on the right should fit in properly like login page. That'd be better.
Take you time

**Comment by Walexz01** [comment]
Ok sir

**Comment by narayan954** [comment]
> you can let the signup form be scrollable but the image on the right should fit in properly like login page. That'd be better. Take you time

let's have this as the next issue, currently we should just focus on the new UI

**Comment by Walexz01** [comment]
ok sir

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution!

**Comment by Walexz01** [comment]
@narayan954 aalways happy to contribute sir ❤️

**Pull request merged**
