### PR TITLE
Profile modal

### PR DESCRIPTION
**Pull request by anamika7153**
- I have added update pic button on the profile-pic modal.
Closes: #632 

## Screenshots
| | |
|---|-----|
| My profile | Other's profile |
|  |  |

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
why are same lines repeating? is this working??  line 270 to 365 are repeating from 385 perhaps, can you please recheck?

**Comment by anamika7153** [comment]
> why are same lines repeating? is this working?? line 270 to 365 are repeating from 385 perhaps, can you please recheck?

Yeah, because before on clicking the avatar a modal opens ans shows the user image in a circle.
What i have done is, on clicking the logged in user will see his profile pic and below it the option to update photo and dor other users the avatar displays profile pic in a square taking full height and width of the modal.

|||
|---|-----|
|Before|after|
|Screenshot_20230713_075416_Chrome|252707752-e16d819d-5c2f-4aec-b242-99d50bf22f18|
|Screenshot_20230713_075008_Chrome|252707578-74ed98a2-ee75-49fc-8cd2-456fa5afc8f7|

**Comment by narayan954** [comment]
> > why are same lines repeating? is this working?? line 270 to 365 are repeating from 385 perhaps, can you please recheck?
> 
> before, on clicking the avatar a modal opens and shows the user image in a circle. What i have done is, on clicking the logged in user will see his profile pic and below it the option to update photo and dor other users the avatar displays profile pic in a square taking full height and width of the modal. It is repeating because the profile page displays the image and edit pic and modal displays it too.
> 
> Before	after
> image	252707752-e16d819d-5c2f-4aec-b242-99d50bf22f18
> image	image

ohh okay

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
