### PR TITLE
made home page ui responsive

### PR DESCRIPTION
**Pull request by anamika7153**
Close: #630 

- Home page UI was not responsive below 800px and below 1200px.

### Video (BEFORE)

https://github.com/narayan954/dummygram/assets/66116440/03ecb544-640a-49cb-8920-df96d9e91099

### Video (AFTER)

https://github.com/narayan954/dummygram/assets/66116440/62ae1742-c96a-4523-87cd-e07460f70838

### CODE REVIEW

**Comment by narayan954** [comment]
It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts. 
image

Can you please try fixing that?

**Comment by anamika7153** [comment]
> It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts. image
> 
> Can you please try fixing that?



> It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts. image
> 
> Can you please try fixing that?

Hey @narayan954 , I have checked while inspecting and it was working fine. Could you please elaborate a bit as what is the issue?

**Comment by narayan954** [comment]
> > It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts. image
> > Can you please try fixing that?
> 
> > It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts. image
> > Can you please try fixing that?
> 
> Hey @narayan954 , I have checked while inspecting and it was working fine. Could you please elaborate a bit as what is the issue?

Hello, actually some style properties were changed in pr #643 and in between padding property got overridden at some places I suppose. That might be the issue.

**Comment by anamika7153** [comment]
> > > It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts.
> > > Can you please try fixing that?
> > 
> > 
> > > It was fine until I merged the master branch in it :(, the mobile screens are not working well unfortunately. Also this affects profile page as well because both have same css for posts.
> > > Can you please try fixing that?
> > 
> > 
> > Hey @narayan954 , I have checked while inspecting and it was working fine. Could you please elaborate a bit as what is the issue?
> 
> Hello, actually some style properties were changed in pr #643 and in between padding property got overridden at some places I suppose. That might be the issue.

On it

**Comment by narayan954** [comment]
> @narayan954
> 
> * Also the posts cards were not centrally aligned before.
> 
> Before	Updated
> image	image
> image	image
> image	image
> image	image



> @narayan954
> 
> * Also the posts cards were not centrally aligned before.
> 
> Before	Updated
> image	image
> image	image
> image	image
> image	image

right, thanks for fixing!

**Comment by narayan954** [comment]
reviewing, and upgraded issue to level 2

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @anamika7153 little changes requested. 
In row mode there's whitespace in the sidebar as you can see in the screenshot 
image
Also reduce the bottom margin please
image
we may fix the scroll to top button later...

**Comment by narayan954** [comment]
> Hi @anamika7153 little changes requested. In row mode there's whitespace in the sidebar as you can see in the screenshot image Also reduce the bottom margin please image we may fix the scroll to top button later...

Also, in mobile displays mode, there's a slight inconsistency of margin
image

**Comment by narayan954** [comment]
> Hi @anamika7153 little changes requested. In row mode there's whitespace in the sidebar as you can see in the screenshot !Also reduce the bottom margin please

Also slightly reduce the top margin 
image

**Comment by anamika7153** [comment]
> > Hi @anamika7153 little changes requested. In row mode there's whitespace in the sidebar as you can see in the screenshot !Also reduce the bottom margin please
> 
> Also slightly reduce the top margin image

noted

**Comment by anamika7153** [comment]
> Hi @anamika7153 little changes requested. In row mode there's whitespace in the sidebar as you can see in the screenshot image Also reduce the bottom margin please image we may fix the scroll to top button later...

bottom margin??? talking about bottom margin of post?

**Comment by narayan954** [comment]
> > Hi @anamika7153 little changes requested. In row mode there's whitespace in the sidebar as you can see in the screenshot image Also reduce the bottom margin please image we may fix the scroll to top button later...
> 
> bottom margin??? talking about bottom margin of post?

yes, for the last post

**Comment by anamika7153** [comment]
@narayan954 Have a look :)

**Comment by narayan954** [comment]
> @narayan954 Have a look :)

gotcha

**Comment by narayan954** [comment]
Thanks for fixing this! :)

**Comment by anamika7153** [comment]
> Thanks for fixing this! :) I'm really bad with css ;-;

You're welcome :) You'll get there. Even I'm not too good.

**Pull request merged**
