### PR TITLE
Feat: Migrated to vite

### LINKED ISSUE #18: Use Vite
**Is your feature request related to a problem? Please describe.**
The app was created using create-react-app, which is great, but there are so many dependency errors.
PS: This issue is related to #2

**Describe the solution you'd like**
Use [vite](https://vitejs.dev/) instead, which is super fast and has great dx

**Describe alternatives you've considered**
[NONE]

**Additional context**
[NONE]

### PR DESCRIPTION
**Pull request by mathiasayivor**
Closes #18

### CODE REVIEW

**Comment by narayan954** [comment]
Hello @mathiasayivor First of all you have done lots of work , hats off to you. 
Secondly, in the migration some features got busted. So we have to fix them up before merging the PR , so it doesn't affect the master branch. I have highlighted some of the bugs in the comment section of the app itself xD. And am searching for other bugs as well.
Thank you.

**Comment by mathiasayivor** [comment]
@narayan954 Can you indicate where the issue is?
So far, I can see there's a conflict with package-lock.json, but it's not a good idea to try resolving such a huge file. The best thing I think we can do is to remove and add the package-lock.json to .gitignore since it's not important atm.

**Comment by narayan954** [comment]
package-lock.json isn't the issue but the project . I checked your PR, clean installed npm dependencies , started server with npm run dev and it ran fine. But error occurred while testing the project. I was not able to comment properly, whenever I clicked post button on comment section in any of post(card) , the page crashed white, console says:
image

I guest error lies within it only

**Comment by mathiasayivor** [comment]
Oh I know the cause...

**Comment by mathiasayivor** [comment]
Oh I know the cause...

**Comment by mathiasayivor** [comment]
I used `nanoseconds` property on `comment.timestamp` for the unique `key` prop, since it was a loop (`src/components/Post.jsx` line: 55)

**Comment by mathiasayivor** [comment]
> I used `nanoseconds` property on `comment.timestamp` for the unique `key` prop, since it was a loop (`src/components/Post.jsx` line: 55)

Guess the best thing to do is to use a different prop

**Comment by narayan954** [comment]
you're absolutely right !!

**Comment by narayan954** [comment]
Thanks a lot for your contribution @mathiasayivor you taught me a lot with this :)

**Pull request merged**
