### PR TITLE
Updated the css file

### PR DESCRIPTION
**Pull request by Code1705**
colour of the background and  border are being changed

### CODE REVIEW

**Comment by Code1705** [comment]
@narayansoni I have committed  changes for the styling of UI of the app, could you please merge my PR?

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi there, 
with these changes there're some new issues, like dark mode won't function properly, leftover areas seem odd and some marked in the image below, please take a look
css pr

**Comment by Code1705** [comment]
I have made certain changes now , could you please merge my PR?

**Review by narayan954 — CHANGES_REQUESTED** [review]
bro the website has gone full rainbow now, please consider using simple colours, like any social media does, neither too bright nor too dull. Simple does it! . Dark mode looks more like a pink mode.

**Comment by Code1705** [comment]
Ok I will change it.

**Comment by Code1705** [comment]
now could you check my commits? and please merge my PR

**Review by narayan954 — APPROVED** [review]
Looks good to me now!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Pull request merged**
