### PR TITLE
Added Feedback File

### PR DESCRIPTION
**Pull request by kharshita590**
I HAVE ADDED THE FILE PLACE WHERE YOU WANTED TO PLACE IT, PLEASE MAKE ENSURE TO INSTALL EMAIL-JS LIBEARY.

### CODE REVIEW

**Comment by narayan954** [comment]
> I HAVE ADDED THE FILE PLACE WHERE YOU WANTED TO PLACE IT, PLEASE MAKE ENSURE TO INSTALL EMAIL-JS LIBEARY.

you're supposed to add the library to the project(in package.json). Have you tested this? please provide screenshots

**Review by narayan954 — CHANGES_REQUESTED** [review]
I checked the code... it needs some modifications and styling. Also, I'd suggest this to be a modal instead. You may use the material UI modal and add these fields and the functionalities.We can add a little button at the bottom right corner of our application for feedback and it should open the modal.... If you're able to implement this I can increase the issue level label.

**Comment by kharshita590** [comment]
Sure I will apply the changes

**Comment by kharshita590** [comment]
You can add the label

**Comment by narayan954** [comment]
> You can add the label

it's okay I'll add the labels in pr after merging

**Pull request closed without merging**
