### PR TITLE
Adding User Profile Page

### PR DESCRIPTION
**Pull request by SubhamB2003**
Issue Solved: #269 

Hey, I am adding the user Profile feature.

Previous:
image

After Adding:
image

Profile Page
image

### CODE REVIEW

**Comment by narayan954** [comment]
@SubhamB2003 please link the correct issue

**Comment by SubhamB2003** [comment]
> please link the correct issue

You are closing the issue I raised : (
how can I add the correct link

**Comment by narayan954** [comment]
> > please link the correct issue
> 
> You are closing the issue I raised : ( how can I add the correct link

Please read the comment I put there, don't take it personal. It's just a code of conduct I guess to not create duplicate issue. Get yourself assigned on the original issue and mention this pr.

**Comment by narayan954** [comment]
Also about this pr, try to fix some of the code review issues as mentioned by [deepsource analysis of your changes](https://app.deepsource.com/gh/narayan954/dummygram/run/db74a5b8-0ba4-494f-970e-61856b9a5174/javascript/).

Ps: You don't need to solve all of them but the critical ones

**Comment by SubhamB2003** [comment]
> > > please link the correct issue
> > 
> > 
> > You are closing the issue I raised : ( how can I add the correct link
> 
> Please read the comment I put there, don't take it personal. It's just a code of conduct I guess to not create duplicate issue. Get yourself assigned on the original issue and mention this pr.

Sorry, I am not telling you in that sense actually I am not getting which link I can add so I was telling you this

**Comment by SubhamB2003** [comment]
> 

Yeah I can check

**Comment by narayan954** [comment]
> > > > please link the correct issue
> > > 
> > > 
> > > You are closing the issue I raised : ( how can I add the correct link
> > 
> > 
> > Please read the comment I put there, don't take it personal. It's just a code of conduct I guess to not create duplicate issue. Get yourself assigned on the original issue and mention this pr.
> 
> Sorry, I am not telling you in that sense actually I am not getting which link I can add so I was telling you this

It's okay, I think you missed the link I put there to the original issue (issue #49)

**Comment by SubhamB2003** [comment]
> > > > > please link the correct issue
> > > > 
> > > > 
> > > > You are closing the issue I raised : ( how can I add the correct link
> > > 
> > > 
> > > Please read the comment I put there, don't take it personal. It's just a code of conduct I guess to not create duplicate issue. Get yourself assigned on the original issue and mention this pr.
> > 
> > 
> > Sorry, I am not telling you in that sense actually I am not getting which link I can add so I was telling you this
> 
> It's okay, I think you missed the link I put there to the original issue (issue #49)

Hey, can I change the bind functions to a normal functions?
image

I already remove the unused variable and template literal

**Pull request closed without merging**
