### PR TITLE
Style changes to submenu

### PR DESCRIPTION
**Pull request by mahekkg**
Style changes to submenu : to match with both light and dark mode.
Please Review and provide feedback.

Screenshot (386)
Screenshot (385)

### CODE REVIEW

**Comment by narayan954** [comment]
Also, please provide some margin right for the dialog box.

**Comment by mahekkg** [comment]
Hey @narayan954
There wasn't much change required in the navbar and submenu is part of navbar so worked on it , sorry for the confusion.
And, yes will provide the required margin to the dialog box.
Thank you .

**Comment by mahekkg** [comment]
> Hey @narayan954 There wasn't much change required in the navbar and submenu is part of navbar so worked on it , sorry for the confusion. And, yes will provide the required margin to the dialog box. Thank you .

Also I got a mail saying PR run failed.
Please help me out I am new to Open source
Thank you.

**Comment by narayan954** [comment]
> Hey @narayan954 There wasn't much change required in the navbar and submenu is part of navbar so worked on it , sorry for the confusion. And, yes will provide the required margin to the dialog box. Thank you .

oh it's alright then

**Comment by narayan954** [comment]
> > Hey @narayan954 There wasn't much change required in the navbar and submenu is part of navbar so worked on it , sorry for the confusion. And, yes will provide the required margin to the dialog box. Thank you .
> 
> Also I got a mail saying PR run failed. Please help me out I am new to Open source Thank you.

this repository has many github actions running and hence some might fail, you don't need to worry about all of them. just the actions you can see in the pull request like greet user, greetings, deepsource transformation and javascript, etc. You may also check the deepsource javascript analysis to get some feedback by ai analysis of code, but that's not too compulsory

**Comment by narayan954** [comment]
can you please verify by yourself the changes you're trying to make on this pr ? I think there's some duplicate code block now

**Comment by narayan954** [comment]
> Hey , I tried from my end . Please let me know if it is resolved and guide me if it is not. Help would be appreciated. Thankyou

Hi Mahek, actually the changes you had done have been overwritten by some of the commits, so the actual implementation is lost in those early commits.

You have many options but the simplest one would be to reset this branch as there are too many commits, and apply the original changes (you may check the earlier commits)

**Comment by narayan954** [comment]
> Hey , I tried from my end . Please let me know if it is resolved and guide me if it is not. Help would be appreciated. Thankyou

ping me in discord with the error you're facing Mahek

**Comment by mahekkg** [comment]
okay will work on it

**Comment by narayan954** [comment]
> okay will work on it

okay, feel free to ask if any doubt

**Comment by mahekkg** [comment]
Please check I have tried from my end and is showing in my forked repo.
Thank you.

**Comment by narayan954** [comment]
> Please check I have tried from my end and is showing in my forked repo. Thank you.

I think you're unable to push the changes to remote, please try pushing using the -f flag, for example ` git push -f `

**Comment by narayan954** [comment]
Also Mahek, you're pushing to master branch and not this Mahek branch

**Comment by mahekkg** [comment]
> Also Mahek, you're pushing to master branch and not this Mahek branch

should I push it to mahek  as git push origin mahek -f
Or to master as git push origin master -f

**Comment by narayan954** [comment]
> > Also Mahek, you're pushing to master branch and not this Mahek branch
> 
> should I push it to mahek as git push origin mahek -f Or to master as git push origin master -f

git push origin mahek -f should do

**Pull request closed without merging**
