### PR TITLE
Improve signup page and fix validation issue

### PR DESCRIPTION
**Pull request by SubhamB2003**
solves #695 

Fixed: 
confirm  password and password validation issue and adding a scroll option on the signUp page

https://github.com/narayan954/dummygram/assets/94003231/051e09be-d048-4bc8-b3e7-31336864b01e

### CODE REVIEW

**Comment by narayan954** [comment]
> solves #695
> 
> Fixed: confirm password and password validation issue and adding a scroll option on the signUp page
> 
>  dummaygramAuth.mp4

Hi @SubhamB2003 UI of login page is getting pretty bad with this, original one is a lot better. You just had to handle the scrolling part for image in signup page. Make it synchronous to login page, just enable scrolling to the form or make the form small in size to fit in.

**Comment by SubhamB2003** [comment]
@narayan954 Hey, is this ok?

https://github.com/narayan954/dummygram/assets/94003231/eb7024b9-2222-465c-be52-49133e6e187e

**Comment by narayan954** [comment]
> @narayan954 Hey, is this ok?
> 
>  dummaygram.mp4

yes it is good!, though it's cropped which is perhaps the image's fault as well, as it's too wide.

**Comment by SubhamB2003** [comment]
> > @narayan954 Hey, is this ok?
> > dummaygram.mp4
> 
> yes it is good!, though it's cropped which is perhaps the image's fault as well, as it's too wide.

Yes, so can I update it

**Comment by narayan954** [comment]
> > > @narayan954 Hey, is this ok?
> > > dummaygram.mp4
> > 
> > 
> > yes it is good!, though it's cropped which is perhaps the image's fault as well, as it's too wide.
> 
> Yes, so can I update it

sure, go ahead!

**Comment by narayan954** [comment]
reviewing when I get right back

**Review by narayan954 — APPROVED** [review]
looks good to me! :)

**Pull request merged**
