### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Code1705**
please merge my PR under JWOC

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi there, looks like you've not fetched the latest changes, please fetch them and in that change, I already am covering a decent part of readme by a card. You can update that section to be not just about admin, but something like merge of about me and feedback /suggestions.My [email](narayansoni954@gmail.com) and [Linkedin](https://www.linkedin.com/in/narayan-soni/) if it needs to be mentioned. 
Also, this pr doesn't solve the issues as you mentioned in your issue like "The new features to be added on point is missing and contribution guidelines could be made attractive and point wise" as you said.

**Comment by Code1705** [comment]
Ok definately I will work on it

**Comment by Code1705** [comment]
as per your I have committed the changes, please could you merge my pr?

**Comment by narayan954** [comment]
> as per your I have committed the changes, please could you merge my pr?

I'm traveling right now and will look into asap but before that please correct the spelling mistakes in latest commit

**Comment by Code1705** [comment]
Ok definately

**Comment by Code1705** [comment]
done as per u said , merge my PR

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi there, it looks good to me! except from the feedback section, where headings are at the center(inconsistent with other headings) and sentences are not properly aligned. Also div with center prop was not closed. Sorry for the delay.

**Comment by Code1705** [comment]
as per your instruction i made the required changes , you can merge it now.

**Comment by narayan954** [comment]
> as per your instruction i made the required changes , you can merge it now.

you didn't follow the complete instruction when I told you to fetch the latest changes. this branch was 95 commits behind.Now these changes need more fix :(

**Comment by narayan954** [comment]
I will fix them now, but please you need to learn from this mistake.

**Review by narayan954 — APPROVED** [review]
lgtm!

**Pull request merged**
