### PR TITLE
Added Neon Logo to DummyGram

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #398

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
lgtm

**Comment by narayan954** [comment]
forgot to add the labels, have added now.
Btw Is it only me or does this logo look better than new one being used?

**Comment by Palakkgoyal** [comment]
Yes, I also thought about it and I think the old one was better compared to the new.

**Comment by Palakkgoyal** [comment]
> > Yes, I also thought about it and I think the old one was better compared to the new.
> 
> right, am thinking of adding it back with a blue tint this time

Can I create a new issue for it?

**Comment by narayan954** [comment]
> > > Yes, I also thought about it and I think the old one was better compared to the new.
> > 
> > right, am thinking of adding it back with a blue tint this time
> 
> Can I create a new issue for it?

yes you can! that'd be good

**Comment by Palakkgoyal** [comment]
Thanks a lot. Actually I want to work on many issues to increase my score, I also sent about 10 PRs to other repositories such as Animating button and Pranjay Poddar but, didn't get any response(they are active but, work very slow). Till now my all merged PRs are of dummygram and I am really happy about it. This repo and your support helped me a lot in contributing.

**Comment by narayan954** [comment]
> Thanks a lot. Actually I want to work on many issues to increase my score, I also sent about 10 PRs to other repositories such as Animating button and Pranjay Poddar but, didn't get any response(they are active but, work very slow). Till now my all merged PRs are of dummygram and I am really happy about it. This repo and your support helped me a lot in contributing. Screenshot (598)

woah! I'm really happy to hear that! Thanks a lot for being cooperative as well!

**Comment by Palakkgoyal** [comment]
Yes, it is and I also very happy about that.

**Pull request merged**
