### PR TITLE
Enhancement Request - Date Indication in Messaging Section #1314

### PR DESCRIPTION
**Pull request by Swetha-Baskaran**
Issue Id: #1314 

Screenshots: 
image
image
image
image
image

Glad to work with Dummygram :)

@narayan954 Pls review my PR. Let me know for further corrections and changes.

### CODE REVIEW

**Comment by narayan954** [comment]
Hi @Swetha-Baskaran this looks really great, will be reviewing asap, meanwhile can you please fix those minor issues mentioned by solarcloud analysis? 

Thanks

**Comment by narayan954** [comment]
I've fixed that minor issue, can you please enable "Allow edits by maintainers" so I can update :)

**Comment by narayan954** [comment]
> I've fixed that minor issue, can you please enable "Allow edits by maintainers" so I can update :)

Also, now we are automatically scrolled to the top of the windows, instead of being scrolled to the bottom. I'm looking into it, can you assist please?

**Comment by Swetha-Baskaran** [comment]
> I've fixed that minor issue, can you please enable "Allow edits by maintainers" so I can update :)

done

**Comment by Swetha-Baskaran** [comment]
> > I've fixed that minor issue, can you please enable "Allow edits by maintainers" so I can update :)
> 
> Also, now we are automatically scrolled to the top of the windows, instead of being scrolled to the bottom. I'm looking into it, can you assist please?

sure I'll try raise other pr for that issue

**Comment by narayan954** [comment]
> > > I've fixed that minor issue, can you please enable "Allow edits by maintainers" so I can update :)
> > 
> > 
> > Also, now we are automatically scrolled to the top of the windows, instead of being scrolled to the bottom. I'm looking into it, can you assist please?
> 
> sure I'll try raise other pr for that issue

It's related to how we handle scrollTop function. It's conflicting while loading more messages. We can solve this later. I'm merging this now :)

**Comment by narayan954** [comment]
Thanks for your contribution! This looks really good, I couldn't even think of this :)

**Pull request merged**
