### PR TITLE
Improved the aesthetics of this project #1317

### PR DESCRIPTION
**Pull request by devArghya-0155**
Changes made are listed below:

1.  Changed the _background colour_ of _body, sidebar, navbar and suggestions_. It works correctly in both light mode and dark mode.
2.  Improved post structure -
     -  Changed the _position_ of post caption. It is now above the post.
     -  Fixed the _colour_ of post caption. It had a grey background in dark mode.
     -  Changed the _structure_ of post nav. _Post stats_ (number of likes and comments) and the option to _like, comment, share & bookmark_ occupy the same place.
     -  Added interactive screentips to each button.
     - Changed the background of comment box to separate it from other post content. Works correctly in both dark and light mode.

3. Made some minor changes to few other components.

image

image

Please let me know if there are any errors. I will fix them at the earliest.

### CODE REVIEW

**Comment by narayan954** [comment]
hi @devArghya-0155 I'm traveling right now and will be free in a day, I'll review this pr then.Thanks for your patience

**Comment by devArghya-0155** [comment]
> hi @devArghya-0155 I'm traveling right now and will be free in a day, I'll review this pr then.Thanks for your patience

Please review my pr and let me know what changes need to be made.

**Comment by narayan954** [comment]
> > hi @devArghya-0155 I'm traveling right now and will be free in a day, I'll review this pr then.Thanks for your patience
> 
> Please review my pr and let me know what changes need to be made.

Yes, really sorry for the delay, actually it's having merge conflicts which can only be solved on a desktop, that's why the delay

**Comment by narayan954** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=narayan954_dummygram&pullRequest=1329) **Quality Gate failed**
> Failed conditions
> 
> [B Reliability Rating on New Code](https://sonarcloud.io/dashboard?id=narayan954_dummygram&pullRequest=1329) (required ≥ A)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=narayan954_dummygram&pullRequest=1329)
> 
> idea Catch issues before they fail your Quality Gate with our IDE extension SonarLint [SonarLint](https://www.sonarsource.com/products/sonarlint/features/connected-mode/?referrer=pull-request)

also, can you please check the code analysis review, it's smelling something

**Comment by narayan954** [comment]
hi @devArghya-0155 can you please check if it's responsive... it's breaking in every screen

**Comment by devArghya-0155** [comment]
> hi @devArghya-0155 can you please check if it's responsive... it's breaking in every screen
> 
> references: image image image

I am working on these issues now.

**Comment by narayan954** [comment]
closed due to inactivity

**Pull request closed without merging**
