### PR TITLE
Bug fix 929

### PR DESCRIPTION
**Pull request by biplavmz**
bug fix for #929  and #1002 
image

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @biplavmz it's adding to the ir-responsiveness in mobile view, please fix
image

**Comment by narayan954** [comment]
check for all screens

**Comment by biplavmz** [comment]
Hii @narayan954 is it ok
image

**Comment by biplavmz** [comment]
Hii @narayan954  I have push the changes pls check and merge

**Review by narayan954 — CHANGES_REQUESTED** [review]
please refactor the css you added

**Comment by biplavmz** [comment]
Hii @narayan954  I have fix the issue and refactor the css can you please check and merge my pr

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @biplavmz , the issue persists, 
image
Can you please check this

**Comment by biplavmz** [comment]
Hii @narayan954  i have fix the issue pls check

image

**Comment by narayan954** [comment]
> Hii @narayan954 i have fix the issue pls check
> 
> image

right, checking!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
