### PR TITLE
Issue 414

### LINKED ISSUE #414: [FEATURE] Post items should be in row
### Description

I think for larger devices post items should be in center as there is a lot of empty space on left and right.
scrnli_02_06_2023_18-58-37

Please assign this to me under gssoc

### Screenshots

_No response_

### Additional information

We'll add a toggle to switch between row format and column format.

### PR DESCRIPTION
**Pull request by Soulpurr**
for larger screens more than  800 px now the card items are in row.
fixes #414 
[scrnli_03_06_2023_16-45-39.webm](https://github.com/narayan954/dummygram/assets/92094765/29341313-a62e-42cd-ab4a-429c0b6a63bf)

### CODE REVIEW

**Comment by Soulpurr** [comment]
@narayansoni pls verify and approve this .

**Comment by Soulpurr** [comment]
@narayan954 can you pls check and approve this pr .

**Comment by Soulpurr** [comment]
@narayan954 ahh  it's alright

**Comment by Soulpurr** [comment]
> > > @narayan954 ahh  it's alright
> > 
> > 
> > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> 
> so users can view these posts as they wish. This'd be a unique feature for our app as well

Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?

**Comment by narayan954** [comment]
> > > > @narayan954 ahh  it's alright
> > > 
> > > 
> > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > 
> > so users can view these posts as they wish. This'd be a unique feature for our app as well
> 
> Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?

just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.

**Comment by Soulpurr** [comment]
> > > > > @narayan954 ahh  it's alright
> > > > 
> > > > 
> > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > 
> > > 
> > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > 
> > 
> > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> 
> just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.

Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?

**Comment by Soulpurr** [comment]
> > > > > > @narayan954 ahh  it's alright
> > > > > 
> > > > > 
> > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > 
> > > > 
> > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > 
> > > 
> > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > 
> > 
> > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> 
> Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?

Actually that's a great idea,I can work on it 

> > > > > > > @narayan954 ahh  it's alright
> > > > > > 
> > > > > > 
> > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > 
> > > > > 
> > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > 
> > > > 
> > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > 
> > > 
> > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > 
> > 
> > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> 
> exactly

So I can work on it and make changes in this pr only?

**Comment by narayan954** [comment]
> > > > > > > @narayan954 ahh  it's alright
> > > > > > 
> > > > > > 
> > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > 
> > > > > 
> > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > 
> > > > 
> > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > 
> > > 
> > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > 
> > 
> > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> 
> Actually that's a great idea,I can work on it
> 
> > > > > > > > @narayan954 ahh  it's alright
> > > > > > > 
> > > > > > > 
> > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > 
> > > > > > 
> > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > 
> > > > > 
> > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > 
> > > > 
> > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > 
> > > 
> > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > 
> > 
> > exactly
> 
> So I can work on it and make changes in this pr only?

Yes you can work on this :) and make changes however you like... Also, we'll update the issue to level 2.

**Comment by Soulpurr** [comment]
> > > > > > > > @narayan954 ahh  it's alright
> > > > > > > 
> > > > > > > 
> > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > 
> > > > > > 
> > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > 
> > > > > 
> > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > 
> > > > 
> > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > 
> > > 
> > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > 
> > 
> > Actually that's a great idea,I can work on it
> > > > > > > > > @narayan954 ahh  it's alright
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > > 
> > > > > > > 
> > > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > > 
> > > > > > 
> > > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > > 
> > > > > 
> > > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > > 
> > > > 
> > > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > > 
> > > 
> > > exactly
> > 
> > 
> > So I can work on it and make changes in this pr only?
> 
> Yes you can work on this :) and make changes however you like... Also, we'll update the issue to level 2.

@narayan954  i have added that feature as requested you can check and verify and also pls increase the level of issue from 1 to 2.

**Comment by Soulpurr** [comment]
> > > > > > > > > @narayan954 ahh  it's alright
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > > 
> > > > > > > 
> > > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > > 
> > > > > > 
> > > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > > 
> > > > > 
> > > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > > 
> > > > 
> > > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > > 
> > > 
> > > Actually that's a great idea,I can work on it
> > > > > > > > > > @narayan954 ahh  it's alright
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > > > 
> > > > > > > > 
> > > > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > > > 
> > > > > > > 
> > > > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > > > 
> > > > > > 
> > > > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > > > 
> > > > > 
> > > > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > > > 
> > > > 
> > > > exactly
> > > 
> > > 
> > > So I can work on it and make changes in this pr only?
> > 
> > 
> > Yes you can work on this :) and make changes however you like... Also, we'll update the issue to level 2.
> 
> @narayan954 i have added that feature as requested you can check and verify and also pls increase the level of issue from 1 to 2.

[scrnli_06_06_2023_18-13-02.webm](https://github.com/narayan954/dummygram/assets/92094765/45f875f4-c16f-4c87-8245-b315751078f8)

**Comment by narayan954** [comment]
> > > > > > > > > @narayan954 ahh  it's alright
> > > > > > > > 
> > > > > > > > 
> > > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > > 
> > > > > > > 
> > > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > > 
> > > > > > 
> > > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > > 
> > > > > 
> > > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > > 
> > > > 
> > > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > > 
> > > 
> > > Actually that's a great idea,I can work on it
> > > > > > > > > > @narayan954 ahh  it's alright
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > @Soulpurr I thought of something... how about we add a trigger/button to change the alignment for bigger screens???
> > > > > > > > 
> > > > > > > > 
> > > > > > > > so users can view these posts as they wish. This'd be a unique feature for our app as well
> > > > > > > 
> > > > > > > 
> > > > > > > Like what on clicking a button the alignment changes from column to row or you want to load more post on clicking a button?
> > > > > > 
> > > > > > 
> > > > > > just like in some apps where we can switch/toggle between row display or column display. A small trigger icon button at top right corner beneath the navbar.
> > > > > 
> > > > > 
> > > > > Like on clicking that button the alignment changes from col to row or vica versa.Just like a theme toggling button right?
> > > > 
> > > > 
> > > > exactly
> > > 
> > > 
> > > So I can work on it and make changes in this pr only?
> > 
> > 
> > Yes you can work on this :) and make changes however you like... Also, we'll update the issue to level 2.
> 
> @narayan954 i have added that feature as requested you can check and verify and also pls increase the level of issue from 1 to 2.

Great, done... reviewing this!

**Comment by narayan954** [comment]
It's not responsive for small screens... can you check?? 
image

**Comment by Soulpurr** [comment]
> It's not responsive for small screens... can you check?? image

Uhh let me just fix that bte any more changes so that I can fix them all at once

**Comment by narayan954** [comment]
> > It's not responsive for small screens... can you check?? image
> 
> @narayan954 verify it if its fixed or not.

yes it's fixed... reviewing this

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
