### PR TITLE
Chnges made as per mentioned

### LINKED ISSUE #652: Text color change in Dark mode
### What would you like to share?

In the dark mode of the login page,the text is not visible sue to black color,
I would like to fix this under gssoc'23

### Additional information

image

### PR DESCRIPTION
**Pull request by shruuti321**
Closes #652 as per the changes mentioned in the issue section
Modified the forgot password and sign in links by changing the font size and adding hovering effects.
image

### CODE REVIEW

**Comment by shruuti321** [comment]
@narayan954  kindly review and approve

**Comment by shruuti321** [comment]
Kindly let me know if the changes are sufficient enough

**Comment by narayan954** [comment]
> changes

reviewing

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution!

**Comment by shruuti321** [comment]
@narayan954  kindly assign the gssoc label to this PR so that it can be counted as a contribution on the leaderboard

**Pull request merged**
