### PR TITLE
Improvement in form ui + buttons for signup and login form both

### PR DESCRIPTION
**Pull request by akanksha984**
image
image
image
image

I have updated the ui of buttons as well as for form, also, I have done it for both signIn and signUp form in dark and light mode both. Hope you like it @narayan954 

Issue reference to : https://github.com/narayan954/dummygram/issues/799
https://github.com/narayan954/dummygram/issues/800

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @akanksha984 can you please check the responsiveness as it's breaking for mobile devices now :/
imageimage



Also, oauth buttons are not centered
image

**Comment by akanksha984** [comment]
image
image
image
image

@narayan954 please check it now I have fixed it

**Comment by narayan954** [comment]
> image image image image
> 
> @narayan954 please check it now I have fixed it

aight!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution! 
I couldn't find much improvements in buttons and input fields that's why I'm grading this as level 2

**Comment by akanksha984** [comment]
Should I work more upon the ui of the button ? For the input fields I have changed the color according to the theme so, I found it good, and for button there was of lot of confusing going with the theme so i made some changes to it

**Comment by narayan954** [comment]
> Should I work more upon the ui of the button ? For the input fields I have changed the color according to the theme so, I found it good, and for button there was of lot of confusing going with the theme so i made some changes to it

It's okay for now, we'll look into that later

**Comment by akanksha984** [comment]
Ok sir as you wish 😊

**Pull request merged**
