### PR TITLE
Added save favourite option

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Added save your favourite post option 

For that i have stored the id and post to the localstorage and when the user checks his profile he can see his saved posts.

### When you haven't saved anything

Screenshot (6)

## When you save any post

Screenshot (7)

## saved posts

Screenshot (9)

### CODE REVIEW

**Comment by Deepanshu0703** [comment]
This is issue number #82 assigned to me

**Comment by Deepanshu0703** [comment]
Okay np

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
thanks for your contribution! :)

**Comment by Deepanshu0703** [comment]
Thanks

**Pull request merged**
