### PR TITLE
Added Profile Page

### PR DESCRIPTION
**Pull request by SubhamB2003**
Issue Solved #49 

@narayan954 Hey, I made the changes in this PR.

### CODE REVIEW

**Comment by narayan954** [comment]
> Issue Solved #49
> 
> @narayan954 Hey, I made the changes in this PR.

Hi @SubhamB2003 please don't create a new pr for every change. That's not how the github flow works. You may have just updated your original pr.

**Comment by narayan954** [comment]
Now this pull request has some conflicts, try to resolve them

**Comment by narayan954** [comment]
Also, format your code and keep the imports sorted, that increases readability and maintainability.

**Comment by SubhamB2003** [comment]
> > Issue Solved #49
> > @narayan954 Hey, I made the changes in this PR.
> 
> Hi @SubhamB2003 please don't create a new pr for every change. That's not how the github flow works. You may have just updated your original pr.

I don't know how to do can you help me ?

**Comment by narayan954** [comment]
> I really apologize. I don't know that much about Github. I know if there is some issue in my PR I have to close that one and create a new PR so I do that.
> There is a conflict so I deleted the fork repo and now I can't open the original PR.
> 
> Can I open a new PR? I promise it would be the last time.

chill brother, it's okay. If there's an issue with a pr you can actually fix it, deleting won't help if you're creating the pr with same branch, as it'll create the same issue, only history conversation shall be removed. Show me the error and I'll help you fix that

**Comment by SubhamB2003** [comment]
> 

Thank you for understanding.

Actually, I delete the fork repo and I am not able to reopen it.

**Comment by narayan954** [comment]
> > 
> 
> Thank you for understanding.
> 
> Actually, I delete the fork repo and I am not able to reopen it.
> So, there is the only option is to open a new PR
> 
> 

ping me on discord

**Comment by SubhamB2003** [comment]
> > > 
> > 
> > 
> > Thank you for understanding.
> > Actually, I delete the fork repo and I am not able to reopen it.
> > So, there is the only option is to open a new PR
> 
> ping me on discord

ok

**Pull request closed without merging**
