### PR TITLE
(other):implemented lazy-load and error boundary

### LINKED ISSUE #580: Implement Code Splitting with React Lazy and Suspense for Better Performance[OTHER]
## Description
The current React-based project [dummygram](https://github.com/narayan954/dummygram) is experiencing performance issues due to the large file sizes that need to be loaded. To enhance the loading time and overall user experience, it is necessary to implement code splitting using React Lazy and Suspense.

Code splitting enables us to split our JavaScript code into smaller chunks and load them only when required. By doing so, we can reduce the initial load time and improve the perceived performance of the application. React Lazy and Suspense are the recommended tools for achieving code splitting in React applications.

## Objective
1. Implement code splitting using React Lazy and Suspense to load components on demand.
2. Identify large files or components that can be split into separate bundles.
3. Refactor the codebase to import these components using React Lazy dynamically.
4. Utilize the Suspense component to display fallback content while the lazy-loaded components are being loaded.
5. Test the code splitting implementation thoroughly to ensure it works correctly across different scenarios.

## Expected Benefits
1. Reduced initial loading time of the application.
2. Improved performance and responsiveness, especially for slower network connections or devices.
3. Enhanced user experience with faster page rendering and interactivity.
4. Optimal resource utilization by loading only the required components.
5. Easier maintenance and scalability as components can be loaded and updated independently.

Additionally, it is recommended to create an error boundary to catch and handle any errors that might occur during the lazy loading process. This will assist in better debugging and provide a graceful fallback experience for the users when errors occur.

Please let me know if you need any further assistance or clarification regarding this issue.

### PR DESCRIPTION
**Pull request by Kalyan-velu**
Fixes #580 

Changes:

- Installed package: `react-error-boundary`
- Implemented suspense
- Improved efficiency of the Error view

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @Kalyan-velu , can you please take a look at this, the css is breaking :/
image

**Comment by Kalyan-velu** [comment]
@narayan954 ok

**Comment by Kalyan-velu** [comment]
@narayan954 I think everything is ok now.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
> @narayan954 I think everything is ok now.

Thanks for fixing :)

**Comment by narayan954** [comment]
Upgrading to level 3 for adding error boundary as well.

**Comment by Kalyan-velu** [comment]
@narayan954 thanks

**Pull request merged**
