### PR TITLE
Search Icon Bug Fixed

### PR DESCRIPTION
**Pull request by Mayank77maruti**
when in mobile mode , we toggled from dark mode to light mode , the search button was having a bug that was fixed.

### CODE REVIEW

**Comment by narayan954** [comment]
> when in mobile mode , we toggled from dark mode to light mode , the search button was having a bug that was fixed.

Hi @Mayank77maruti , do try to mention the issue number you've solved. That helps in closing that issue as completed.

**Comment by Mayank77maruti** [comment]
I would make sure to put the issue number from the next time onwards.

**Review by narayan954 — APPROVED** [review]
Looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Pull request merged**
