### PR TITLE
Added dark mode feature

### PR DESCRIPTION
**Pull request by Kritika30032002**
issue #31 

Added Dark Mode Feature with dark mode toggle button and dark Mode effects to the website.

### CODE REVIEW

**Comment by narayan954** [comment]
Also, the toggle button is overlapping with the scroll to top button's affected area and hence sometimes we're clicking on scroll to top button instead of toggle dark mode.

**Comment by Kritika30032002** [comment]
> Hello there @Kritika30032002, can you please use react packages (like react-dark-mode-toggle ) for dark mode instead? It'd be better for the project. Thanks.

Okay

**Comment by Kritika30032002** [comment]
> Also, the toggle button is overlapping with the scroll to top button's affected area and hence sometimes we're clicking on scroll to top button instead of toggle dark mode.

Okay

**Comment by Kritika30032002** [comment]
> Hello there @Kritika30032002, can you please use react packages (like react-dark-mode-toggle ) for dark mode instead? It'd be better for the project. Thanks.

@narayan954  I am not much familiar with react though I tried but not able to do this through react package.

If you can accept this PR then I will remove the overlapping of  the toggle button and scroll to top button. You can let me know your decision.

**Comment by narayan954** [comment]
> > Hello there @Kritika30032002, can you please use react packages (like react-dark-mode-toggle ) for dark mode instead? It'd be better for the project. Thanks.
> 
> @narayan954  I am not much familiar with react though I tried but not able to do this through react package.
> 
> If you can accept this PR then I will remove the overlapping of  the toggle button and scroll to top button. You can let me know your decision.

okay fine , you can go ahead.

**Comment by Kritika30032002** [comment]
> > > Hello there @Kritika30032002, can you please use react packages (like react-dark-mode-toggle ) for dark mode instead? It'd be better for the project. Thanks.
> > 
> > 
> > @narayan954  I am not much familiar with react though I tried but not able to do this through react package.
> > If you can accept this PR then I will remove the overlapping of  the toggle button and scroll to top button. You can let me know your decision.
> 
> okay fine , you can go ahead.

Okay

**Comment by Kritika30032002** [comment]
> Also, the toggle button is overlapping with the scroll to top button's affected area and hence sometimes we're clicking on scroll to top button instead of toggle dark mode.

@narayan954 
Scroll to top button is in center and dark mode button is in right side


image

**Comment by Kritika30032002** [comment]
@narayan954 its done!
You can have a look to it!

**Comment by narayan954** [comment]
> @narayan954 its done!
> You can have a look to it!

okay thanks! will take a look asap

**Comment by Kritika30032002** [comment]
@narayan954

**Review by narayan954 — APPROVED** [review]
lgtm

**Comment by narayan954** [comment]
Thanks for your contribution :)

**Pull request merged**
