### PR TITLE
Fix data lose that was happening due to creating post

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR fixes issue no. #649 
It was somewhat tricky to find but, very crucial to implement. Everything was working fine with the user collection but, whenever the user create a new post his/her data in the collection got replaced with an array that contain just a ref for a single post.
Actually, there was a mistake in updating the doc. Instead of updating doc, it was getting replaced by the set function.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
there's still a problem in this I believe. If an old user who doesn't exists in the users collection uploads a post, then this would crash and he won't be able to create a post. Actually this function was set to update initially and I found this error and suggested him to somehow upsert the post(create user document if it doesn't exists and add the post ther). Unfortunately there's this error as well. Need to think of a solution. Checking if user exists first and then uploading a post seems costly and slow

**Comment by Palakkgoyal** [comment]
Yes, its very costly to check everytime for the user. I think as the website is still under development we should remove all users and apply users collection correctly. As currently here are only developers and not real users.
What do you think?

**Comment by narayan954** [comment]
> Yes, its very costly to check everytime for the user. I think as the website is still under development we should remove all users and apply users collection correctly. As currently here are only developers and not real users. What do you think?

you're correct! We should start fresh! I'm changing the db :)

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
