### PR TITLE
Moved saved posts from sidebar to profile

### LINKED ISSUE #1101: [FEATURE] Remove saved posts from sidebar and move to profile
### Description

Currently, the saved posts icon is on the sidebar. I want to move it to profile like instagram. So, their will be two options for the current user one is saved and second is feed and only one for other user that is feed if they visit other user profile.

### Screenshots

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1101 
I have removed the saved posts from sidebar to profile. I have used an async function to fetch saved posts instead of a useEffect because I think people just don't visit it every time they open their profile and this async function will only run once when the saved button is clicked for the first time. By this it will not create any extra requests.
Screenshot 2023-08-04 153111

### CODE REVIEW

**Comment by narayan954** [comment]
> This PR closes #1101 I have removed the saved posts from sidebar to profile. I have used an async function to fetch saved posts instead of a useEffect because I think people just don't visit it every time they open their profile and this async function will only run once when the saved button is clicked for the first time. By this it will not create any extra requests. Screenshot 2023-08-04 153111

oh alright! can you resolve the merge request?

**Comment by Palakkgoyal** [comment]
Yes, sure.

**Comment by Palakkgoyal** [comment]
I solved the merge conflict and also set a loader if the posts are loading and a message if there are no posts.

**Comment by Palakkgoyal** [comment]
Resolve conflict.

**Review by narayan954 — APPROVED** [review]
looks awesome to me! we need a shimmer effect after this though

**Comment by Palakkgoyal** [comment]
Yes sure.

**Pull request merged**
