### PR TITLE
Add dropdown menu in sidebar

### LINKED ISSUE #1017: Change the look of setting and logout button
### Description

The current logout and setting button have poor text visibility and also doesn't look good. I want to give them a new look.

### Screenshots

Screenshot 2023-07-28 194928

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1017 
I have added a dropdown list and also made it darkmode compatible. It works fine. I haven't dynamically added the name of user in the sidebar and replaced it with `Me` because whenever the page loads it take time to fetch user data. which result in delay in showing the name which doesn't look good.
Screenshot 2023-07-29 202718

### CODE REVIEW

**Comment by narayan954** [comment]
> This PR closes #1017 I have added a dropdown list and also made it darkmode compatible. It works fine. I haven't dynamically added the name of user in the sidebar and replaced it with `Me` because whenever the page loads it take time to fetch user data. which result in delay in showing the name which doesn't look good. Screenshot 2023-07-29 202718

I think, as we are already querying the user's collection for user data and extracting username we can extract other details as well like name... Also, the auth object might've displayName already. We're not making any extra query. 
Ps: Here comes another big suggestion, also, we don't even need to fetch username for every component, we're using getUsername method eveywhere. Instead we can create a context for the user right?

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
> > This PR closes #1017 I have added a dropdown list and also made it darkmode compatible. It works fine. I haven't dynamically added the name of user in the sidebar and replaced it with `Me` because whenever the page loads it take time to fetch user data. which result in delay in showing the name which doesn't look good. Screenshot 2023-07-29 202718
> 
> I think, as we are already querying the user's collection for user data and extracting username we can extract other details as well like name... Also, the auth object might've displayName already. We're not making any extra query. Ps: Here comes another big suggestion, also, we don't even need to fetch username for every component, we're using getUsername method eveywhere. Instead we can create a context for the user right? The one provided by firebase aint enough
> 
> edit: as I am going though pr, it seems you've followed this only! thank you! and also, if you're querying name from user's collection and updating it in profile, it might not get reflected without reloading. As a solution, we can use `auth.currentUser.displayName` which works right until we refresh the page and sidebar would crash as it can't get the displayName property... so I think I'll add condition to reflect both, but `auth.currentUser.displayName` first to make it fast and responsive.

but wait, `me` was already better, why did I resolve ;-;

**Comment by Palakkgoyal** [comment]
> > This PR closes #1017 I have added a dropdown list and also made it darkmode compatible. It works fine. I haven't dynamically added the name of user in the sidebar and replaced it with `Me` because whenever the page loads it take time to fetch user data. which result in delay in showing the name which doesn't look good. Screenshot 2023-07-29 202718
> 
> I think, as we are already querying the user's collection for user data and extracting username we can extract other details as well like name... Also, the auth object might've displayName already. We're not making any extra query. Ps: Here comes another big suggestion, also, we don't even need to fetch username for every component, we're using getUsername method eveywhere. Instead we can create a context for the user right? The one provided by firebase aint enough
> 
> edit: as I am going though pr, it seems you've followed this only! thank you! and also, if you're querying name from user's collection and updating it in profile, it might not get reflected without reloading. As a solution, we can use `auth.currentUser.displayName` which works right until we refresh the page and sidebar would crash as it can't get the displayName property... so I think I'll add condition to reflect both, but `auth.currentUser.displayName` first to make it fast and responsive.

Yes, its inefficient to query for userdata on every page. Instead we should get it only at one place then use caching or session storage or context to deliver it to other components and if the data updates then, we can also update it in the context or any other method.

**Comment by narayan954** [comment]
> > > This PR closes #1017 I have added a dropdown list and also made it darkmode compatible. It works fine. I haven't dynamically added the name of user in the sidebar and replaced it with `Me` because whenever the page loads it take time to fetch user data. which result in delay in showing the name which doesn't look good. Screenshot 2023-07-29 202718
> > 
> > 
> > I think, as we are already querying the user's collection for user data and extracting username we can extract other details as well like name... Also, the auth object might've displayName already. We're not making any extra query. Ps: Here comes another big suggestion, also, we don't even need to fetch username for every component, we're using getUsername method eveywhere. Instead we can create a context for the user right? The one provided by firebase aint enough
> > edit: as I am going though pr, it seems you've followed this only! thank you! and also, if you're querying name from user's collection and updating it in profile, it might not get reflected without reloading. As a solution, we can use `auth.currentUser.displayName` which works right until we refresh the page and sidebar would crash as it can't get the displayName property... so I think I'll add condition to reflect both, but `auth.currentUser.displayName` first to make it fast and responsive.
> 
> Yes, its inefficient to query for userdata on every page. Instead we should get it only at one place then use caching or session storage or context to deliver it to other components and if the data updates then, we can also update it in the context or any other method.

agreed, will create an issue

**Pull request merged**
