### PR TITLE
Modal change

### PR DESCRIPTION
**Pull request by saurabhbakolia**

### CODE REVIEW

**Review by saurabhbakolia — COMMENTED** [review]
Nice

**Comment by narayan954** [comment]
> image
> 
> I don't know why it is showing errors. I am using "" variable. But still showing that error for many variables.

are you talking about deepsource check?

**Comment by narayan954** [comment]
why are you creating multiple prs?

**Comment by saurabhbakolia** [comment]
ok, I was unaware of that. 
I have one question. I am committing multiple times, then I push the code. It should include in the last PR right?

**Pull request closed without merging**
