### PR TITLE
updated button style

### PR DESCRIPTION
**Pull request by 1010varun**
Screenshot from 2023-02-26 00-37-41
Screenshot from 2023-02-26 00-38-18

@narayan954 please review and merge my pr.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
hi varun, can you please add some hover animation for the button as well.

**Comment by 1010varun** [comment]
@narayan954 I have added on-hover effect. Kindly review and merge my pr.

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by narayan954** [comment]
Thanks for the contribution!

**Pull request merged**
