### PR TITLE
updated like button

### PR DESCRIPTION
**Pull request by 1010varun**

### CODE REVIEW

**Comment by 1010varun** [comment]
[Screencast from 2023-02-22 14-19-40.webm](https://user-images.githubusercontent.com/104075461/220569842-b3ee9f6c-5250-4bb1-b807-f6de3a0faf69.webm)

@narayan954 I have updated the like button please merge my pr.

**Comment by 1010varun** [comment]
@narayan954 please review and merge my pr

**Comment by 1010varun** [comment]
@narayan954,

I noticed that you merged the master branch with my pull request #187. I'm wondering if this means that my pull request will still be merged or not. Could you please explain the situation to me?

If my pull request isn't going to be merged, then I won't receive any points for it. Can you please help me out with this?

Thank you.

**Comment by narayan954** [comment]
> @narayan954,
> 
> I noticed that you merged the master branch with my pull request #187. I'm wondering if this means that my pull request will still be merged or not. Could you please explain the situation to me?
> 
> If my pull request isn't going to be merged, then I won't receive any points for it. Can you please help me out with this?
> 
> Thank you.

I was just updating this branch with master, it doesn't have anything to do with my decision of merging this pr or not, I am going to review this pr and merge it if it's eligible. Don't worry, you'll receive points for your work! :)

**Comment by narayan954** [comment]
You didn't change your branch name, that's why you're getting confused, please work on separate branch for separate issue, so to avoid confusions and conflicts in the future, 
Thanks

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by 1010varun** [comment]
> You didn't change your branch, and worked on your previous branch only that's why you're getting confused, please work on separate branch for separate issue, so to avoid confusions and conflicts in the future, 
> Thanks

Okay sir I will keep this in mind :)
Thank you sir

**Pull request merged**
