### PR TITLE
Added MUI alerts to replace browser alerts ⚠️

### PR DESCRIPTION
**Pull request by warmachine028**
# Use MUI Alerts 📐
- I Pritam Kundu have worked for #51 

## Changes Made
- Used Material UI to add Snackbar Component
- Added Snackbar to repalce browser alerts
  - Log In
  - Sign Up
  - Image Upload Error
  - Sign In Error
  - Firebase Error
   
- Replaced all alerts and error messages and with Snackbar Notifications

## Screenshots:

- Logging In
logged in

- Logging Out
logout

- Error Messages
error

- Creating Post 
193544547-8cf9be78-34b5-4fd8-8364-60414cf82ad1

### CODE REVIEW

**Comment by mathiasayivor** [comment]
@warmachine028 Instead of creating a custom component, you might want to consider [notistack](https://notistack.com/), which has an imperative API and makes it easy to display snackbars, without having to handle their open/close state

**Comment by warmachine028** [comment]
I have already closed 2 PRs regarding this issue. @narayan954 said that the notification was alright but it had issues in the merge conflicts. So I had to scrap out everything and begin from the start. Besides it was clearly mentioned in the PR to use MUI alerts so I did it. Using notistack means i have to start again from scratch which seems quite cumbersome at this point

**Comment by mathiasayivor** [comment]
I understand your pain, but notistack is actually quite easy to implement IMO.
I'd try implementing it in your fork so you can proceed if that's cool with you?

**Comment by warmachine028** [comment]
> I understand your pain, but notistack is actually quite easy to implement IMO. Using your current solution means we'd have to be prop-drilling or repeating code if we need to re-use the snackbar in other components. I'd try implementing it in your fork so you can proceed if that's cool with you.

Sure you can try implementing in my fork

**Review by narayan954 — APPROVED** [review]
Everything's fine and thanks a lot for taking the step!, Just a question related to prompt when signing out 
image
Can this be done using notistack as well ?

**Comment by narayan954** [comment]
> This can be done using a dialogBox

oh okayy

**Pull request merged**
