### PR TITLE
Added dark mode in sidebar

### PR DESCRIPTION
**Pull request by sumitkr2000**
Hey @narayan954 I have added dark mode in sidebar. Please review my pr and merge it. Thank you!

- Issue no. #272 

## Before:-

image

## After:-

image

### CODE REVIEW

**Comment by narayan954** [comment]
> Hey @narayan954 I have added dark mode in sidebar. Please review my pr and merge it. Thank you!
> 
> * Issue no. [[FEATURE] Improving UI of the home page #272](https://github.com/narayan954/dummygram/issues/272)
> 
> ## Before:-
> image
> 
> ## After:-
> image

I think you've linked the incorrect issue, please correct

**Comment by narayan954** [comment]
Also, this was an assigned issue...

**Review by narayan954 — APPROVED** [review]
lgtm

**Comment by sumitkr2000** [comment]
> Also, this was an assigned issue...

Ohh sorry...i thought i told you when i created sidebar...that i will add dark mode in another pr... that's why i did it.

**Comment by narayan954** [comment]
> > Also, this was an assigned issue...
> 
> Ohh sorry...i thought i told you when i created sidebar...that i will add dark mode in another pr... that's why i did it.

yeah, that was a different issue and he raised and claimed it. It's okay this time but make sure to claim it next time.

**Comment by sumitkr2000** [comment]
Okay bro thanks

**Pull request merged**
