### PR TITLE
Revert "Merge pull request #86 from bhoopesh369/bhoopesh"

### PR DESCRIPTION
**Pull request by narayan954**
This reverts commit f7c7066156d1258b8c89e061ffbdbc67471bc7f0, reversing changes made to 20cf6cf2420d35ca22f2a40e6a3fc283d7a5f17d.

### CODE REVIEW

**Comment by narayan954** [comment]
production is failing with #86 so reverting it until a solution is found

**Comment by bhoopesh369** [comment]
> production is failing with #86 so reverting it until a solution is found

Is the problem with the code?

**Comment by bhoopesh369** [comment]
@narayan954  The website works perfectly when its run locally

**Comment by bhoopesh369** [comment]
image

**Comment by bhoopesh369** [comment]
I think the issue is with other prs

**Comment by narayan954** [comment]
yeah, you might be right bhoopesh, I'll look into it .

**Comment by narayan954** [comment]
but this problem arises with your pr only and reverting it fixed it.

**Comment by narayan954** [comment]
> I think the issue is with other prs

or the older posts, as it's failing in the build

**Pull request merged**
