### PR TITLE
Modified index.css file

### PR DESCRIPTION
**Pull request by vk20july**
@narayansoni  Please review my code

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
it's not working for different screens, for example mobile. Can you find why or fix it?

**Comment by vk20july** [comment]
ok let me see

**Comment by vk20july** [comment]
@narayan954 can you provide the screenshot because here it is working fine

**Comment by narayan954** [comment]
> ok let me see

images for your reference. btw this issue arrived in pr #218 if that helps 
mobile view
web view

**Comment by vk20july** [comment]
ok sir thank you

**Comment by vk20july** [comment]
@narayan954 made the required changes please review

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
