### PR TITLE
Comment delete feature added

### PR DESCRIPTION
**Pull request by bhoopesh369**
Heyy I have completed 90% in implementing the delete commentrs feature 
But i dont know exactly how to delete from the firebase database.
I think you'd know the correct firebase commands 
So I have made this PR .

Only the User who made the comment will be shown a delete button.
and only they can delete it 

only the firebase part is remaining

@narayan954 @narayansoni

### CODE REVIEW

**Comment by bhoopesh369** [comment]
I spent a lot of time learning firebase commands but could only do 90% of the work

**Comment by bhoopesh369** [comment]
@narayan954

**Comment by narayan954** [comment]
okay I guess you can take idea from the #78, I'll share more information soon. Thanks for the great work!

**Comment by narayan954** [comment]
comment delete command should be as simple as 
``` sh
	async function deleteComment(){
      await db.collection("posts").collection("comments").doc(commentId).delete();
    }
```
Hope this helps!

**Comment by bhoopesh369** [comment]
> comment delete command I guess should be as simple as
> 
> ```shell
> 	async function deleteComment(){
>       await db.collection("posts").doc(postId).collection("comments").doc(commentId).delete();
>     }
> ```
> 
> Hope this helps!

But the commentId is not there?
@narayan954 @narayansoni

**Comment by bhoopesh369** [comment]
heyy thanks i will work on it

**Pull request closed without merging**
