### PR TITLE
Improved the background and card style of Dummygram

### PR DESCRIPTION
**Pull request by Frs2304**
Due to technical issues with the dark mode feature on Dummygram, it was not working correctly. As a result, I have decided to keep the background color white, instead of using a gradient. This will allow both the `light-mode` and `dark-mode` features to be available on Dummygram and that too working correctly. 
To enhance the aesthetics of the card style on Dummygram, I have made improvements to the border color. Specifically, I have given the border a black color for the light mode, and I have changed the border color to white for the dark mode, which creates a 3D effect. These changes will help to create a more visually appealing and cohesive user experience on Dummygram.
Solved issue #213

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hello @Frs2304 , there might've been some changes, also there's a merge conflict so can you fetch the latest changes and check if it works fine? Also, can you reduce the area above and below the picture content of post as perhaps there's too much white space on the post or give your suggestion on this.

**Comment by narayan954** [comment]
Also, can you provide screenshot for the changes , it'd easy to look :)

**Comment by Frs2304** [comment]
> Also, can you provide screenshot for the changes , it'd easy to look :)

Ok..I will share you the screenshot once I fixed all the issues.

**Comment by narayan954** [comment]
Comment when it's ready for review

**Comment by narayan954** [comment]
Please create a new pr for this issue. Closing this as unattended

**Pull request closed without merging**
