### PR TITLE
Setting page with sound settings

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #620 
Screenshot 2023-07-03 232811

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
is level 2 label ok or level 3, what do you think??

**Comment by Palakkgoyal** [comment]
I think it should be level3 cause it take more than I thought. In this I have created a UI, setup routes, make a centralized system for turning off sounds which can be further useful in turning off a particular sound, finding content to write and make it responsive(not completely but, sufficient for now).
If it is ok from your side to give level3 then, I think we should go for it.

**Comment by narayan954** [comment]
> I think it should be level3 cause it take more than I thought. In this I have created a UI, setup routes, make a centralized system for turning off sounds which can be further useful in turning off a particular sound, finding content to write and make it responsive(not completely but, sufficient for now). If it is ok from your side to give level3 then, I think we should go for it.

correct! I thought so :P

**Pull request merged**
