### PR TITLE
Sticky navbar issue

### PR DESCRIPTION
**Pull request by Sar-thak-3**
#179 issue

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
please remove unnecessary changes in package.json and vite configuration. merge with the master branch

**Comment by narayan954** [comment]
The problem was , you merged the main branch with the master, which was running separate. Reverting that commit fixed it.

**Comment by Sar-thak-3** [comment]
> The problem was , you merged the main branch with the master, which was running separate. Reverting that commit fixed it.

Is it fine now, or I need to make any other changes?

**Review by narayan954 — CHANGES_REQUESTED** [review]
please fill in some margin between the post and navbar like old view

**Comment by narayan954** [comment]
@Sar-thak-3 you can follow the comment :)

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi there! these changes are breaking the layout in mobile view, can you try fixing that?
breaking responsivenes

**Comment by Sar-thak-3** [comment]
> Hi there! these changes are breaking the layout in mobile view, can you try fixing that? breaking responsivenes

image
In my system it's working fine, kindly check it

**Comment by narayan954** [comment]
Okay I understand, but can you give it more margin, like in the original case. That way it looks nice.
And also, can you fix the issue 2 as mentioned in the image below
sticky navbar

thanks

**Comment by narayan954** [comment]
closing as inactive and no response

**Pull request closed without merging**
