### PR TITLE
fix: Replaced WebP File Format with instead of using jpg, png Files Format in Suitable Files

### PR DESCRIPTION
**Pull request by NarendraKoya999**
### Proposed Changes
- **Replaced webp Images File Format with intead of using jpg, png File Format in Full Project Directory even in Codebase Files also.**

### For Reviewers
- **I cross checked Every Minude Details 2 to 3 Times after My Changes Made.**
- **So, I hope In my Side, No Mistakes Happened. If any unwanted Mistakes in Respective Project Directory, then Please Quote Me.**
- **One Suggestion to You,  Some Project related Files have Unused Images Files Imported in Multiple Files. Also, Most of the Files are not Used in Most of the Files. But, Existed those Files in Assets Section. This effects due to Unnecessary Data Consuming.**

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @narayan954 . Please Review on this PR as soon as Possible. Also, add Valid Level Label under GSSOC'23. Because of I have involved Full Project Directory. Thank You !

**Comment by narayan954** [comment]
> ### GSSOC'23 Contributor
> ### Fixes Issue No : #1168
> ### Proposed Changes
> * **Replaced webp Images File Format with intead of using jpg, png File Format in Full Project Directory even in Codebase Files also.**
> 
> ### For Reviewers
> * **I cross checked Every Minude Details 2 to 3 Times after My Changes Made.**
> * **So, I hope In my Side, No Mistakes Happened. If any unwanted Mistakes in Respective Project Directory, then Please Quote Me.**
> * **One Suggestion to You,  Some Project related Files have Unused Images Files Imported in Multiple Files. Also, Most of the Files are not Used in Most of the Files. But, Existed those Files in Assets Section. This effects due to Unnecessary Data Consuming.**

Hi @NarendraKoya999 thanks a lot for fixing them. By the way as you're saying there're many unused imports as well, can you remove them as well? As you've gone the code and know there occurrence, it'd be best if you remove them :). I'll upgrade this issue to level 2 then.

**Comment by NarendraKoya999** [comment]
@narayan954 .I will go with your arguments.But, You can add Leve 2 Label after these changes.Actually, the Issue sentence is easy.Suppose any typo mistake happens,then Total Page UI appeared in different Way.So, Please think advancing regarding of  considered Level Label .Thank You!

**Comment by NarendraKoya999** [comment]
Hi @narayan954 . I Deleted Unused Import Statements in Multiple Files. Please Review on that. If all is Ok. Without Late, Please Merged with Valid Level Label. Thank You !

**Comment by narayan954** [comment]
> Hi @narayan954 . I Deleted Unused Import Statements in Multiple Files. Please Review on that. If all is Ok. Without Late, Please Merged with Valid Level Label. Thank You !

There're syntax errors, you didn't test your changes at all, I'm fixing them

**Review by narayan954 — APPROVED** [review]
you changed the pictures but didn't fix those imports. I've fixed most of these occurrence.

**Comment by narayan954** [comment]
> ### GSSOC'23 Contributor
> ### Fixes Issue No : #1168
> ### Proposed Changes
> * **Replaced webp Images File Format with intead of using jpg, png File Format in Full Project Directory even in Codebase Files also.**
> 
> ### For Reviewers
> * **I cross checked Every Minude Details 2 to 3 Times after My Changes Made.**
> * **So, I hope In my Side, No Mistakes Happened. If any unwanted Mistakes in Respective Project Directory, then Please Quote Me.**
> * **One Suggestion to You,  Some Project related Files have Unused Images Files Imported in Multiple Files. Also, Most of the Files are not Used in Most of the Files. But, Existed those Files in Assets Section. This effects due to Unnecessary Data Consuming.**

I doubt you checked the changes, that's why I have reduced the level label. There's a functionality called search which can quickly show all the affected occurrence and we can fix that.

**Pull request merged**
