### PR TITLE
Feat uploads

### LINKED ISSUE #26: [FEATURE] Enable uploading multiple images
### Description

Currently, users are only able to upload one image at a time. It would be great to enable users to upload multiple images in the same post.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mathiasayivor**
Closes #26

### CODE REVIEW

**Comment by narayan954** [comment]
hello there @mathiasayivor can you please resolve the conflicts so I can take a look?

**Comment by mathiasayivor** [comment]
ok

**Comment by narayan954** [comment]
Sorry, but pr #47 just before you left another merge conflict , can you please resolve one more time, I wont merge anymore before yours.

**Comment by narayan954** [comment]
image
daily limit exceeded, need to implement pagination on an urgent basis

**Comment by mathiasayivor** [comment]
Sure!

**Review by narayan954 — APPROVED** [review]
Looks good and works nicely

**Comment by narayan954** [comment]
Thanks for the contribution! @mathiasayivor

**Pull request merged**
