### PR TITLE
feat: Login page changes made

### PR DESCRIPTION
**Pull request by shruuti321**
I have changed the login page background colour in both light and dark modes and also provided for margin form top.
image
image

### CODE REVIEW

**Comment by shruuti321** [comment]
@narayan954 I am encountering this error while pushing
Could you please help?
image

**Comment by narayan954** [comment]
> @narayan954 I am encountering this error while pushing
> Could you please help?
> image
> 

as you read in the error, you need to pull first before pushing :) ... so try git pull command first then you can git push.... It's also written in the terminal

**Comment by shruuti321** [comment]
> > @narayan954 I am encountering this error while pushing
> > Could you please help?
> > image
> 
> as you read in the error hint, you need to pull first before pushing :) ... so try git pull command first then you can git push.... It's also written in the terminal as hint

image
This error while pushing was never encountered before

**Comment by narayan954** [comment]
> > > @narayan954 I am encountering this error while pushing
> > > Could you please help?
> > > image
> > 
> > as you read in the error hint, you need to pull first before pushing :) ... so try git pull command first then you can git push.... It's also written in the terminal as hint
> 
> image
> This error while pushing was never encountered before

you're updating wrong branch perhaps, you're working on other branch... try git pull only else git pull origin *branch name*

**Comment by narayan954** [comment]
> > > @narayan954 I am encountering this error while pushing
> > > Could you please help?
> > > image
> > 
> > as you read in the error hint, you need to pull first before pushing :) ... so try git pull command first then you can git push.... It's also written in the terminal as hint
> 
> image
> This error while pushing was never encountered before

it's because, I've pushed a change in your branch and your current local is behind the remote. You need to sync with your remote first :)

**Comment by shruuti321** [comment]
> > > > @narayan954 I am encountering this error while pushing
> > > > Could you please help?
> > > > image
> > > 
> > > 
> > > as you read in the error hint, you need to pull first before pushing :) ... so try git pull command first then you can git push.... It's also written in the terminal as hint
> > 
> > 
> > image
> > This error while pushing was never encountered before
> 
> it's because, I've pushed a change in your branch and your current local is behind the remote. You need to sync with your remote first :)

So sorry for the inconvinience but I have even pulled and merged but still it is showing the same error
image

**Comment by narayan954** [comment]
> > > > > @narayan954 I am encountering this error while pushing
> > > > > Could you please help?
> > > > > image
> > > > 
> > > > 
> > > > as you read in the error hint, you need to pull first before pushing :) ... so try git pull command first then you can git push.... It's also written in the terminal as hint
> > > 
> > > 
> > > image
> > > This error while pushing was never encountered before
> > 
> > 
> > it's because, I've pushed a change in your branch and your current local is behind the remote. You need to sync with your remote first :)
> 
> So sorry for the inconvinience but I have even pulled and merged but still it is showing the same error image

it's alright, try each of these command I am telling below:

`git pull` it pulls to the current branch by default, so it might work for you, if it doesn't, try
`git pull origin log` , this will pull from origin to your log branch, if that shows error try `git pull origin/log log`.


As a final resort, do `git push -f` this will ignore all warnings and push

**Comment by narayan954** [comment]
If none of those work, let me know, I'll revert the commits I made, and then you'll be able to work normally :)

**Comment by shruuti321** [comment]
> If none of those work, let me know, I'll revert the commits I made, and then you'll be able to work normally :)
> 
> Ps: But no, you should know how to fix this error, contact in discord if the issue persists

Could you check if the changes are made

**Comment by narayan954** [comment]
> > If none of those work, let me know, I'll revert the commits I made, and then you'll be able to work normally :)
> > Ps: But no, you should know how to fix this error, contact in discord if the issue persists
> 
> Could you check if the changes are made image

yes, your commits are reflected now!

**Comment by narayan954** [comment]
But your changes are lost, perhaps you deleted the changes?

**Comment by narayan954** [comment]
image
only one line looks changed now :/

**Comment by shruuti321** [comment]
I have made my final commits. Hope this time the changes are being reflected

**Comment by narayan954** [comment]
> I have made my final commits. Hope this time the changes are being reflected

awesome, they look great!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
thanks for your contribution! and do mention your issue, so I can add relevant labels

**Comment by shruuti321** [comment]
Closing #984

**Comment by shruuti321** [comment]
And thankyou so much for providing the guidance and  help on the spot :)

**Comment by shruuti321** [comment]
Label please?

**Comment by narayan954** [comment]
> Label please?

right I forgot, sorry

**Pull request merged**
