### PR TITLE
Feature: Post Delete

### PR DESCRIPTION
**Pull request by tanishk-23**
DeletePost1
DeletePost2

### CODE REVIEW

**Comment by narayan954** [comment]
Hi there @tanishk-23 , anyone can delete posts, even without signing up, you can add some conditions like user exists or not if so, postid.username == user.displayName (not sure about the accuracy)

**Comment by tanishk-23** [comment]
@narayan954 Sure i will do the changes.

**Comment by tanishk-23** [comment]
> postid.username == user.displayName

@narayan954 when I am signing up it is setting username as null

**Comment by narayan954** [comment]
> > postid.username == user.displayName
> 
> @narayan954 when I am signing up it is setting username as null
ohh I need to look into this
and maybe confirm #75

**Comment by tanishk-23** [comment]
> Hi there @tanishk-23 , anyone can delete posts, even without signing up, you can add some conditions like user exists or not if so, postid.username == user.displayName (not sure about the accuracy)

I have fix this issue and post delete feature is working now. You can review the changes.

**Comment by narayan954** [comment]
great, reviewing it right away

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution!

**Comment by tanishk-23** [comment]
Welcome

**Pull request merged**
