### PR TITLE
Created a community chat page for dummygram

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #842 
I have created a community chat room with a nice and simple UI and it is also enough responsive that will give the feel of real chat. I have also set up routes such that whenever someone click on the image of the person who sent the message then they will be routed to that user profile.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @Palakkgoyal this looks great! but there're some issues, sidebar is being affected by these chats,it's going down,bad
prrrr
Along with issues mentioned in pic, New chats are not showing up now as well.
Can you please take a look and try to fix them?

**Comment by narayan954** [comment]
> Hi @Palakkgoyal this looks great! but there're some issues, sidebar is being affected by these chats,it's going down,bad prrrr Along with issues mentioned in pic, New chats are not showing up now as well. Can you please take a look and try to fix them?

image

**Comment by Palakkgoyal** [comment]
Hey @narayan954 I can fix other issues but this navbar issue is not because of me cause I checked today Navbar

> Hi @Palakkgoyal this looks great! but there're some issues, sidebar is being affected by these chats,it's going down,bad prrrr Along with issues mentioned in pic, New chats are not showing up now as well. Can you please take a look and try to fix them?

Hey @narayan954 its not going down. It must be affected by other commit. As you could see my branch has no new commits so the navbar is not going down but you are trying in updated branch and the problem is happening.
But Okay I will try to fix it.
Screenshot (616)

**Comment by Palakkgoyal** [comment]
Ok I will fix all issues.

**Comment by narayan954** [comment]
> Hey @narayan954 I can fix other issues but this navbar issue is not because of me cause I checked today Navbar
> 
> > Hi @Palakkgoyal this looks great! but there're some issues, sidebar is being affected by these chats,it's going down,bad prrrr Along with issues mentioned in pic, New chats are not showing up now as well. Can you please take a look and try to fix them?
> 
> Hey @narayan954 its not going down. It must be affected by other commit. As you could see my branch has no new commits so the sidebar is not going down but you are trying in updated branch and the problem is happening. But Okay I will try to fix it. Screenshot (616)

Ohhh that's the case, I'm sorry. I think in one of the commit, logic is different and hence causing this conflict, could be number #838 . I'll also try finding the cause.
Also, you can remove that windows watermark in yo desktop by activating it using [this less than 2 minutes tutorial](https://github.com/massgravel/Microsoft-Activation-Scripts) (also it's safe, permanent(almost) and open source)

**Comment by narayan954** [comment]
> Ok I will fix all issues.

yes, thank you!, If you're facing issue, let me know, I'll revert and re implement the buggy commit.

**Comment by narayan954** [comment]
I just reverted to the original commit you made, it also has some issues like this in profile page.
image
and my newer messages don't show up at all

**Comment by Palakkgoyal** [comment]
Thanks a lot for fixing. You saved my time. The new one are not showing up might be due to I have set up limit of 20 docs and they are getting fetched based on timestamp from old to new and not from new to old.

**Comment by Palakkgoyal** [comment]
Hey @narayan954 I did the required changes. Can you please check.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
> Hey @narayan954 I did the required changes. Can you please check. And your solution worked. Thanks for sharing. I was so habitual of that mark that it felt like the part of my laptopjoy. Now the space is looking clean :) Screenshot (618)

Sure, it looks great!,Thank you!

**Pull request merged**
