### PR TITLE
Double tap likes bug resolved

### PR DESCRIPTION
**Pull request by Deepanshu0703**
Resolved issue no. #293 

Added double tap like option for text posts too.

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by Deepanshu0703** [comment]
plz assign a level and gssoc label @narayan954

**Comment by narayan954** [comment]
> plz assign a level and gssoc label @narayan954

yes , apologies

**Comment by Deepanshu0703** [comment]
Thanks

**Pull request merged**
