### PR TITLE
Improved UI of search bar for search page

### PR DESCRIPTION
**Pull request by Geeta259**
Improved Search bar section by added some CSS properties on it to look it good.
Add search icon embedded on search bar
Make it responsive in all devices.

Screenshot (640)

@narayan954 issue #791 resolved please check it !!

### CODE REVIEW

**Comment by narayan954** [comment]
Hi @Geeta259 this seems not to be responsive for mobile screens, can you look into it?
image

**Comment by Geeta259** [comment]
> Hi @Geeta259 this seems not to be responsive for mobile screens, can you look into it? image

@narayan954  Now please check !! hope it works fine!!

**Comment by narayan954** [comment]
> > Hi @Geeta259 this seems not to be responsive for mobile screens, can you look into it? image
> 
> @narayan954 Now please check !! hope it works fine!!

of course it does!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for the contribution to dummygram!

**Pull request merged**
