### PR TITLE
💡 [ADD]: CURSOR POINTER FOR EMOJI BUTTON

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
### Description:
- This PR is intended for the Emoji button on `Post.jsx` file
- Added `cursor: pointer` inline style with code linting principles

### Fixes:
- This PR fixed this ISSUE: #395

### CODE REVIEW

**Comment by narayan954** [comment]
> ### Description:
> * This PR is intended for the Emoji button on `Post.jsx` file
> * Added `cursor: pointer` inline style with code linting principles
> 
> ### Fixes:
> * This PR fixed this ISSUE: [[FEATURE] - ADD CURSOR POINTER FOR EMOJI BUTTON WHILE HOVER #395](https://github.com/narayan954/dummygram/issues/395)

enable cursor pointer for both occurrence please

**Comment by 0xabdulkhalid** [comment]
Hello @narayan954, the work has done!.

I added for both occurrence as per your request

**Comment by narayan954** [comment]
> Hello @narayan954, the work has done!.
> 
> I added for both occurrence as per your request

cool, will review and merge asap

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Comment by 0xabdulkhalid** [comment]
Yessir! 🫡

**Pull request merged**
