### PR TITLE
Routing home buttons

### PR DESCRIPTION
**Pull request by NandiniGera**
ABOUT PAGE 
image

CONTRIBUTOR PAGE
image

HELP PAGE
image

GUIDELINES/POLICY PAGE
image

All buttons route back to the home page.

### CODE REVIEW

**Comment by NandiniGera** [comment]
Completes issue #763

**Comment by narayan954** [comment]
> ABOUT PAGE image
> 
> CONTRIBUTOR PAGE image
> 
> HELP PAGE image
> 
> GUIDELINES/POLICY PAGE image
> 
> All buttons route back to the home page.

Hi @NandiniGera content of pages other than `about page` is deviating from center .
Also it's not at all responsive to any screen as you can seen in the screenshot below. Button is lost at most screens.
image


let the content be centred as it is. Some of the approaches are:
1 instead of `back to home` button add this same functionality as a cross/cancel button in the top right corner of the glassy division.
2 add the back button on navbar (not recommended)
3 use the current button but position it such that content remains at center completely as it is and button is visible as well.

**Comment by NandiniGera** [comment]
> > ABOUT PAGE
> > CONTRIBUTOR PAGE
> > HELP PAGE
> > GUIDELINES/POLICY PAGE
> > All buttons route back to the home page.
> 
> Hi @NandiniGera content of pages other than `about page` is deviating from center . Also it's not at all responsive to any screen as you can seen in the screenshot below. Button is lost at most screens. image
> 
> let the content be centred as it is. Some of the approaches are: 1 instead of `back to home` button add this same functionality as a cross/cancel button in the top right corner of the glassy division. 2 add the back button on navbar (not recommended) 3 use the current button but position it such that content remains at center completely as it is and button is visible as well.

Hi, Actually without deviating from the glass division, I was not able to add the button on the Contributors and Guidelines Page:/
Thank you for the approaches, I'll try to fix it asap :)

**Comment by narayan954** [comment]
> > > ABOUT PAGE
> > > CONTRIBUTOR PAGE
> > > HELP PAGE
> > > GUIDELINES/POLICY PAGE
> > > All buttons route back to the home page.
> > 
> > 
> > Hi @NandiniGera content of pages other than `about page` is deviating from center . Also it's not at all responsive to any screen as you can seen in the screenshot below. Button is lost at most screens. image
> > let the content be centred as it is. Some of the approaches are: 1 instead of `back to home` button add this same functionality as a cross/cancel button in the top right corner of the glassy division. 2 add the back button on navbar (not recommended) 3 use the current button but position it such that content remains at center completely as it is and button is visible as well.
> 
> Hi, Actually without deviating from the glass division, I was not able to add the button on the Contributors and Guidelines Page:/ Thank you for the approaches, I'll try to fix it asap :)

ohh alright

**Comment by NandiniGera** [comment]
Added Cross Buttons 

image

image

image

**Comment by NandiniGera** [comment]
image

image

image

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Pull request merged**
