### PR TITLE
Post's height fixed

### LINKED ISSUE #144: [FEATURE] fix post's height
### Description

Currently posts are of uneven lengths, and this is inconsistent, we can fix the post height, so the feed is consistent.
Also fix the height of posts in comments popup and set a minimum height as well.
### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Rishav1707**
### This PR closes the following issue:
closes #144 

### Changes made:
- Added `min-height: 40px;` to the view all comments button.
- Added `max-height: 450px;` to all the post.

### Screenshots:
comments2

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Please check your changes once yourselves as well that they're not breaking anything before creating a pull request :)
image
Content is breaking bad!
Please fix them :)

**Comment by Rishav1707** [comment]
> Please check your changes once yourselves as well that they're not breaking anything before creating a pull request :) image Content is breaking bad! Please fix them :)

I always checked the website before committing a pull request.
From my side the website is running well.

**Comment by narayan954** [comment]
> > Please check your changes once yourselves as well that they're not breaking anything before creating a pull request :) image Content is breaking bad! Please fix them :)
> 
> I always checked the website before committing a pull request. From my side the website is running well.

Well in that case try building the website, check the preview and fix it.

**Comment by narayan954** [comment]
closing as unattended

**Pull request closed without merging**
