### PR TITLE
feat: use image thumbnails when loading posts

### LINKED ISSUE #50: [FEATURE] UX: Use image thumbnails when loading posts
### Description

It'd really be a good UX to use blurred thumbnail images while loading posts and replace them with the actual image when the post is done loading.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mathiasayivor**
Closes #50

### CODE REVIEW

**Review by narayan954 — COMMENTED** [review]
The code looks great, but only one blurry image is covering the whole page as a thumbnail :(.
Also, there's still the loading screen, then the thumbnail screen and then actual post ;/

ss

image

**Comment by mathiasayivor** [comment]
> Also, there's still the loading screen, then the thumbnail screen and then actual post ;/

This sounds like a bad UX, do you have any suggestions?

**Comment by mathiasayivor** [comment]
> The code looks great, but only one blurry image is covering the whole page as a thumbnail :(
> 
> ss
> 

This would be taken care of in #59

**Comment by narayan954** [comment]
> > Also, there's still the loading screen, then the thumbnail screen and then actual post ;/
> 
> This sounds like a bad UX, do you have any suggestions?

Only alternative I could think of is, skeleton like preview from LinkedIn(earlier), but there should be something else we can do right?
I checked Instagram and other socials like twitter and LinkedIn for this and found them using similar loading like ours but with their logos, and in their case, it is too quick. While some social media I saw earlier used to give skeleton structure initially.

So, I think, here we can just display some specific thumbnail initially (not the firebase one as it will still be loading) and as the posts load, they could claim their place.

**Comment by narayan954** [comment]
> > The code looks great, but only one blurry image is covering the whole page as a thumbnail :(
> > ss
> 
> This would be taken care of in #59

correct!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
