### PR TITLE
edit profile pic feature added 

### PR DESCRIPTION
**Pull request by SasiVardhan247**
Solved issues in pr #394. @narayansoni  can you review the changes

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Hi @SasiVardhan247  thanks for contribution but I wanted to remind you one thing you missed. You don't have to work on the master branch, create a separate branch for the changes. Keep the master branch clean so you can safely pull changes from the remote branch.For now, you can clean fetch your master branch from this remote by force pull.

**Comment by narayan954** [comment]
Also, there's no progress indication of profile pic upload. You can implement one like in the upload post.

**Comment by SasiVardhan247** [comment]
> Hi @SasiVardhan247 thanks for contribution but I wanted to remind you one thing you missed. You don't have to work on the master branch, create a separate branch for the changes. Keep the master branch clean so you can safely pull changes from the remote branch.For now, you can clean fetch your master branch from this remote by force pull.

ok sure , nxt time i'll work on seperate branch

**Pull request merged**
