### PR TITLE
Create about page for dummygram

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #552 
I have dynamically added data of number of forks and stars but unable to do the same for number of commits. When I tried to fetch total commits, it only gave me 28 rather than all. I tried some solutions but according to me there is a need of access token by the owner.

### CODE REVIEW

**Comment by narayan954** [comment]
> This PR closes issue no. #552 I have dynamically added data of number of forks and stars but unable to do the same for number of commits. When I tried to fetch total commits, it only gave me 28 rather than all. I tried some solutions but according to me there is a need of access token by the owner.

Hi Palak, sorry I didn't read your comment and implemented it myself. I just read it.

You may look at [this answer](https://stackoverflow.com/a/70610670/15892492) on stackoverflow for the brief description. and the code commits to see the implementation if you wish to understand.

**Comment by narayan954** [comment]
> This PR closes issue no. #552 I have dynamically added data of number of forks and stars but unable to do the same for number of commits. When I tried to fetch total commits, it only gave me 28 rather than all. I tried some solutions but according to me there is a need of access token by the owner.

I think you might be getting 30 instead of 28 as that's the pagination limit of github api for list of commits. I took help of a brilliant solution, give it a read as I mentioned the source.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by Palakkgoyal** [comment]
I checked the solution and I think I get confused due to regex part as I have not used or made any regex by myself. Thanks for sharing.

**Comment by narayan954** [comment]
> I checked the solution and I think I get confused due to regex part as I have not used or made any regex by myself. Thanks for sharing.

It's alright.

**Comment by narayan954** [comment]
another pr I missed the label I guess

**Comment by Palakkgoyal** [comment]
Hey please take care of labels. From onwards I will remind you for my PRs🤦‍♀️😂.

**Comment by narayan954** [comment]
> Hey please take care of labels. From onwards I will remind you for my PRswoman_facepalmingjoy.

hehe sure XD

**Pull request merged**
