### PR TITLE
Create guidelines page for dummygram

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #555 and it is responsive.
Screenshot (577)
Screenshot (578)
Screenshot (579)
Screenshot (580)

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Comment by Palakkgoyal** [comment]
> Thanks for your contribution! :)

Thanks for merging the PR! :)

**Comment by narayan954** [comment]
> @narayan954 check this also

This issue doesn't just involves guidelines page, it also involves refactoring of footer page components, that's why I gave 3 stars.

**Pull request merged**
