### PR TITLE
New Post UI Created and Responsiveness Added

### PR DESCRIPTION
**Pull request by Gurmeet-Singh657**
Hi, Plz have a look on New Mobile and Tablet UI
Issue Number 476

image

image

Plz merge my pull request as a GSSOC'23 Contributor

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution :)

**Comment by Gurmeet-Singh657** [comment]
Thank You so much @narayan954 for providing me the opportunity to work on this repository 🤩

**Comment by narayan954** [comment]
> Thank You so much @narayan954 for providing me the opportunity to work on this repository 🤩

glad to have awesome contributors like you :D

**Pull request merged**
