### PR TITLE
New logo Added

### PR DESCRIPTION
**Pull request by Tisha6661**
Added the new logo for the website and made changes to the desired pages to fit it. The colors match the other elements on the navbar.

Issue Number- #608 

WhatsApp Image 2023-07-03 at 15 17 32

### CODE REVIEW

**Comment by narayan954** [comment]
Hi @Tisha6661 , I was thinking, should we remove the background colour from logo or is it better that way?? If it looks right to you as a user , then it's fine... Also, have you checked dark mode as well?
I'm reviewing pull requests in chronological order :) allow me some time to review this.

**Comment by Tisha6661** [comment]
Yes I tried it without background and some colours, here-
image

But at the end the logo's background goes with the other buttons on navbar, so it looks more nice. Also, i checked it on dark mode, it goes well there.

**Comment by Tisha6661** [comment]
Also i feel that the Ui of the horizontal navbar could be made better, to go with the changes of the logo, should i generate that issue?

**Comment by narayan954** [comment]
> Yes I tried it without background and some colours, here- image
> 
> But at the end the logo's background goes with the other buttons on navbar, so it looks more nice. Also, i checked it on dark mode, it goes well there.

Hi @Tisha6661 , I was checking it, and it doesn't go well with the readme in terms of fit, can you please check that and fix?

**Comment by narayan954** [comment]
Also, in about section, it's not checked for size
image

**Comment by narayan954** [comment]
> Also, in about section, it's not checked for size image

do `git pull` before making any changes so you dont get into a conflict

**Comment by narayan954** [comment]
> Also i feel that the Ui of the horizontal navbar could be made better, to go with the changes of the logo, should i generate that issue?

Yes, sure, also, we can remove the favourites and profile option from there.... Also for your information, there'd be settings option there as well in the drop down.

**Comment by Tisha6661** [comment]
@narayan954 I have done all the changes-

image
image
image
image
image
image

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Pull request merged**
