### PR TITLE
Improve UI - for cards [fixes #33]

### LINKED ISSUE #33: Improve UI - for cards
### Description

Cards for post look really dull or I should say simple. We can design them better with some border/border radius etc. Align the contents to the left similar to a Instagram post

### Screenshots

<p align="center">
  Current
&nbsp; &nbsp; &nbsp; &nbsp;
  Reference
</p>

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by najeebkp**
### Improve UI - for cards [fixes #33]
##description
- Updated card UI
- Added some icons

### CODE REVIEW

**Comment by najeebkp** [comment]
@narayan954 what is this test failed?

**Comment by narayan954** [comment]
> @narayan954 what is this test failed?

actually I had setup some automatic deploy actions , but their key command is not working ie npm ci , so they're all failing . It doesn't affect the current work though, i can still deploy manually

**Comment by najeebkp** [comment]
@narayan954
Cool !
Thank you.

**Comment by narayan954** [comment]
@najeebkp these cards work for posts with images , but don't for post without images. Can you fix this ?
image

**Comment by najeebkp** [comment]
can you create this as a new issue with hacktoberfest label and assign me?

**Comment by narayan954** [comment]
well yes I can.

**Comment by najeebkp** [comment]
dont forget to approve this PR also :)

**Review by narayan954 — APPROVED** [review]

**Pull request merged**
