### PR TITLE
Fixed Issue of Outside Clicking on Opening Profile Panel

### PR DESCRIPTION
**Pull request by Gurmeet-Singh657**
Hey 
I fixed this issue where on Clicking this profile panel box remains open.
But now it will automatically close if the user clicks outside that panel.
Please merge my Pull request.
Thank You
image

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Please mention the issue number you solved on the pr itself, it helps manage the issue well

**Comment by Gurmeet-Singh657** [comment]
Sure 👍 Issue Number 318

**Comment by narayan954** [comment]
> Sure +1 Issue Number 318

yes please mention these in upcoming prs as well

**Comment by narayan954** [comment]
Thanks for your contribution

**Comment by narayan954** [comment]
upgraded the level

**Pull request merged**
