### PR TITLE
Post page UI

### LINKED ISSUE #806: [FEATURE] Post Page UI
### Description

- The current UI pof post page looks very basic and boring.
- I would like to give it an attractive look.

### Screenshots

image

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #806 
I have given a new look to post page. Fixed console errors of post page. Refactored post page files and also deleted files that are not needed.
Screenshot 2023-08-09 202432
Screenshot 2023-08-09 202457
Screenshot 2023-08-09 202721

### CODE REVIEW

**Comment by Palakkgoyal** [comment]
Yes sure. I got the source of problem.

**Comment by Palakkgoyal** [comment]
Fixed.

**Review by narayan954 — APPROVED** [review]
looks awesome to me!

**Comment by narayan954** [comment]
Hi @Palakkgoyal i noticed, you made prs/solved issues of other assignees without even asking/telling them. That's not a good practice. I told you to atleast leave a comment, so others know

**Comment by Palakkgoyal** [comment]
> Hi @Palakkgoyal i noticed, you made prs/solved issues of other assignees without even asking/telling them. That's not a good practice. I told you to atleast leave a comment, so others know you're taking up their issues

Sorry for that I thought they will not say anything as the issues were old.

**Comment by narayan954** [comment]
> > Hi @Palakkgoyal i noticed, you made prs/solved issues of other assignees without even asking/telling them. That's not a good practice. I told you to atleast leave a comment, so others know you're taking up their issues
> 
> Sorry for that I thought they will not say anything as the issues were old.

it's alright, we never know if they're working or not unless we ask. We can also inform them before taking their issue so either they can stop working or call us to stop

**Comment by Palakkgoyal** [comment]
> > > Hi @Palakkgoyal i noticed, you made prs/solved issues of other assignees without even asking/telling them. That's not a good practice. I told you to atleast leave a comment, so others know you're taking up their issues
> > 
> > 
> > Sorry for that I thought they will not say anything as the issues were old.
> 
> it's alright, we never know if they're working or not unless we ask. We can also inform them before taking their issue so either they can stop working or call us to stop

Yes, you are right. I will not do that again :)

**Pull request merged**
