### PR TITLE
made posts in profile page responsive

### PR DESCRIPTION
**Pull request by anamika7153**
Closes: #766 

### Video

https://github.com/narayan954/dummygram/assets/66116440/cb72052f-5338-41f2-9b85-8e2504c77023

### CODE REVIEW

**Comment by anamika7153** [comment]
@narayan954  check now

**Comment by anamika7153** [comment]
> > @narayan954 check now
> 
> it's good, just need some bottom margin I suppose in mobile displays image

consider it done :)

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
> @narayan954 done :)
> 
> image

awesome, merged! :D

**Pull request merged**
