### PR TITLE
Old Post image updation

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #556 
Initially, I was going to dynamically fetch data for post header but I found that it will take too many requests. I mean a seperate request for every post and whenever the home page re-render it fetches again.
So, instead I added static data and in the profile page whenever the user update image then, I made it so that the all posts image also get updated. Along with that I saw that image in the users collection was not getting updated so, I also updated that.

In addition to all this, I also did some other changes, such as dynamically rendering routes for user profile. So, before the url was:
`/dummygram/profile` and it was using some states to check whether it current user or not. Instead I made the url this:
`/dummygram/:username` Hence, we don't need to pass anything while routing. User can also share their profile link unlike before. And I checked everything(I think so). 

NOTE: This might not work with old posts but absolutely fine with new posts.
Pleas merge it as soon as possible as my score is going down and very less days are remaining. @narayan954

### CODE REVIEW

**Review by narayan954 — COMMENTED** [review]
image is not getting updated in preview as well as after upload in the profile image. It updates only after a refresh. sidebar and posts are fine.
image

**Comment by Palakkgoyal** [comment]
> This bug is not because of me. It exists already and I think someone has sent a PR for it already. But, if you want I can work on this.

**Comment by Palakkgoyal** [comment]
> > This bug is not because of me. It exists already and I think someone has sent a PR for it already. But, if you want I can work on this.

**Comment by narayan954** [comment]
> This bug is not because of me. It exists already and I think someone has sent a PR for it. If you want I can work on this as well.

right right right,

**Comment by Palakkgoyal** [comment]
> > This bug is not because of me. It exists already and I think someone has sent a PR for it. If you want I can work on this as well.
> 
> right right, it's alright i'll merge that later

Ohk sure and you can also write right*2(I'll understand)

**Pull request merged**
