### PR TITLE
Give a new look to sidebar

### LINKED ISSUE #1141: Update UI of sidebar
### Description

I want to give a new look to sidebar. I want to make it somewhat similar to instagram sidebar.

### Screenshots

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1141 
Updated the UI of sidebar and made it responsive.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @Palakkgoyal , is this the expected behaviour of the sidebar??
image
it seems a bit off, like the circle around profile card,3 dots on top misaligned...also in notifications page, a pink divider appears. Can you please take a look into that?

**Comment by Palakkgoyal** [comment]
> Hi @Palakkgoyal , is this the expected behaviour of the sidebar?? image it seems a bit off, like the circle around profile card,3 dots on top misaligned... Can you please take a look into that?

Its definitely not the desired behavior. I will remove that active state. And 3 dots misaligned? You mean that I should maintain a fix gap between those 3 dots and the other items?

**Comment by narayan954** [comment]
> > Hi @Palakkgoyal , is this the expected behaviour of the sidebar?? image it seems a bit off, like the circle around profile card,3 dots on top misaligned... Can you please take a look into that?
> 
> Its definitely not the desired behavior. I will remove that active state. And 3 dots misaligned? You mean that I should maintain a fix gap between those 3 dots and the other items?

alright, by misaligned I meant, there's a bigger left margin in other sidebar icons that those 3 dots, so they're not vertically aligned. Also, can we move that profile card to the top similar to this image, perhaps if it looks nice
image

**Comment by Palakkgoyal** [comment]
Yes sure, do you want the menu items to be aligned at top as well?

**Comment by Palakkgoyal** [comment]
Hey, I did some changes. Can you please check.

**Comment by Palakkgoyal** [comment]
Hey, I did some changes. Can you please check.

**Comment by narayan954** [comment]
> Hey, I did some changes. Can you please check. Screenshot 2023-08-08 193403

sure, I am thinking to merge the refactoring pr first so there're very less merge conflicts

**Comment by narayan954** [comment]
Hi @Palakkgoyal , can you please fix these conflicts?

**Comment by Palakkgoyal** [comment]
I have solved the conflict. Can you please check.

**Comment by narayan954** [comment]
> I have solved the conflict. Can you please check.

Hi @Palakkgoyal I just found this css conflicts with comment box css as well, can you please fix?
image

**Comment by Palakkgoyal** [comment]
> > I have solved the conflict. Can you please check.
> 
> Hi @Palakkgoyal I just found this css conflicts with comment box css as well, can you please fix? image

Fixed

**Comment by narayan954** [comment]
> > > I have solved the conflict. Can you please check.
> > 
> > 
> > Hi @Palakkgoyal I just found this css conflicts with comment box css as well, can you please fix? image
> 
> Fixed

when we click on view profile, some one else's profile opens... also, that box is overtaken by sidebar in terms of z index.
Also,profile picture is square now and the box opens very lower than expected. Can you check if you're facing these as well now? I think earlier I didn't face that.
image
image

**Comment by Palakkgoyal** [comment]
I will fix others. But, I checked for this Aditya Roy's profile. I don't know why everytime we are getting there. I thought its happening with me only. I checked for user.uid and I think I checked for everything but still going to this profile. Even I am working on other PR. There also I am getting navigated(sometimes) to this one

**Comment by Palakkgoyal** [comment]
Hey I checked just now that even on the deployed website we are reaching that profile only.

**Comment by Palakkgoyal** [comment]
Hey hey. I get it there is problem with the way we are fetching data.
This function: 
const docRef = db.collection("users", user?.uid);
const docSnap = await docRef.get();

---
You will think that this will return only one doc but, guess what it is returning an array of 87 docs(Perhaps all user docs). Let me check what is wrong.

**Comment by Palakkgoyal** [comment]
Hey I fixed that in my centralize data PR. Check it out.
const docRef = doc(db, "users", user?.uid);
const docSnap = await getDoc(docRef);

**Comment by Palakkgoyal** [comment]
Hey I have fixed the issues. The alignment was due to routing PR

**Comment by narayan954** [comment]
> Hey hey. I get it there is problem with the way we are fetching data. This function: const docRef = db.collection("users", user?.uid); const docSnap = await docRef.get();
> 
> You will think that this will return only one doc but, guess what it is returning an array of 87 docs(Perhaps all user docs). Let me check what is wrong.

thanks a ton for finding that error!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution @Palakkgoyal :)

**Pull request merged**
