### PR TITLE
Help Center page added #1197

### PR DESCRIPTION
**Pull request by biplavmz**
Faq Page added #1197 
image

image

Hii @narayansoni  I have added the help-Center page pls check and pls change the About us Image I Don't have Faq or HelpCenter Image pls change the Image as FAQ or HelpCenter

### CODE REVIEW

**Comment by narayan954** [comment]
> Faq Page added #1197 image
> 
> image
> Hii @narayansoni I have added the help-Center page pls check and pls change the About us Image I Don't have Faq or HelpCenter Image pls change the Image as FAQ or HelpCenter
> 
> image

can you please add a slightly better accordion? and resolve conflicts?

**Comment by biplavmz** [comment]
Hii @narayan954 i have resolve the issue and some changes pls check and merge my pr
image

image

**Comment by biplavmz** [comment]
Hii @narayan954  can you please check and merge my pr

**Comment by narayan954** [comment]
> Hii @narayan954 i have resolve the issue and some changes pls check and merge my pr

thanks I'm checking and merging right away!

**Review by narayan954 — CHANGES_REQUESTED** [review]
why have you named the file notfound.jsx. It doesn't make sense

**Comment by narayan954** [comment]
If we're getting redirected to notfound.jsx, that doesn't mean we update the notfound page itself. Instead we find the source of problem that is, helpcenter page doesn't exist and we need to create one. You should have just followed the other footer pages in pages folder.

**Review by narayan954 — APPROVED** [review]
I had to fix a whole lot of stuffs in this, thus reducing the level to 1

**Pull request merged**
