### PR TITLE
Sign in & Sign Up buttons enhancement

### PR DESCRIPTION
**Pull request by ritika728**
Hey, I have resolved issue #166. Thank you!

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Using reserved prop-names like className and style on custom components hurts readability and makes the code harder to maintain. These props should only be used for DOM nodes like div, a, span, etc. It works in this case but should not be used in practice @ritika728 .
You can take a look into this article https://daily-dev-tips.com/posts/passing-classname-to-components-in-react/ and https://stackoverflow.com/questions/46040733/is-it-possible-to-set-a-classname-on-custom-react-components

**Comment by ritika728** [comment]
Thank you for the information! I have made the required changes. Kindly review and let me know if any more changes are needed @narayan954

**Comment by narayan954** [comment]
> Thank you for the information! I have made the required changes. Kindly review and let me know if any more changes are needed @narayan954

Well done :) but you forgot the DRY principal. You can store that style in a constant variable.

**Review by narayan954 — APPROVED** [review]
you may take a look at this.

**Comment by ritika728** [comment]
> you may take a look at this.

Yes, I got it, thank you so much!

**Pull request merged**
