### PR TITLE
fix Theme button position needs to be changed issue #647

### PR DESCRIPTION
**Pull request by biplavmz**
fix Theme button position needs to be changed issue #647

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
As I mentioned in the issue, I needed it in the sidebar. Please fix that!

**Comment by biplavmz** [comment]
ok @narayan954

**Comment by narayan954** [comment]
> ok @narayan954

Hi @biplavmz , have you started working on that or would you want to hear a modification in plan? I mean, as you had it in navbar it's okay, but please change the icon to fit in the navbar

**Comment by biplavmz** [comment]
ok @narayan954

**Pull request closed without merging**
