### PR TITLE
#511 Bot added

### LINKED ISSUE #511: [FEATURE] Add close old issue bot
### Description

Proposal: Close Old Issue Bot
Description: The Close Old Issue Bot is an automated tool designed to identify and close inactive or resolved issues in a timely manner. It improves issue management efficiency by reducing clutter and ensuring active focus on relevant tasks.
Features:
1. Issue Tracking: Monitors issue activity and identifies those that have remained inactive for a specified period.
2. Automatic Closure: Closes old or resolved issues based on predetermined criteria, promoting a clean and organized issue tracker.
3. Customizable Settings: Allows users to define their own criteria for determining issue activity and closure, adapting to the specific needs of their project.

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by k-deepak04**
closes #511

### CODE REVIEW

**Comment by k-deepak04** [comment]
@narayan954 bro please remove these labels as i have added the bots in other repo also
so it will be counted in spam
Happy to contribute , will look for some other issues
just remove the labels thanks :)

**Comment by narayan954** [comment]
> @narayan954 bro please remove these labels as i have added the bots in other repo also
> so it will be counted in spam
> Happy to contribute , will look for some other issues
> just remove the labels thanks :)

Ohh, okay, I'll remove that.

Thanks a lot for contributing though!

**Comment by k-deepak04** [comment]
@narayan954 Thanks 
Btw I'll see the issues and contribute more valid pr,  if you have something that has to be developed you can tell me i will work on that

**Comment by narayan954** [comment]
> @narayan954 Thanks 
> Btw I'll see the issues and contribute more valid pr,  if you have something that has to be developed you can tell me i will work on that


Thanks a lot!
There're several old inactive issues as well.
The user story feature is yet to be added. Issue is unattended, you may claim that if you wish

**Comment by k-deepak04** [comment]
Sure

**Pull request merged**
