### PR TITLE
Get dynamic notifcation sender data

### LINKED ISSUE #1061: Show user data on notification page
### Description

Currently the notif page only show a static image and also do not navigate the user anywhere. I want to update it such that it shows the image of request sender and also navigate to user id.
I also want to update the profile function of friend request such that it will contain only the id of sender and not other unnecessary data.

### Screenshots

Screenshot 2023-08-01 000751

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1061 
I have added dynamic data for request sender. Now, the link also work which when clicked navigate to user profile.
Screenshot 2023-08-01 171746

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
Looks good to me!

**Comment by narayan954** [comment]
Hi @Palakkgoyal can you please resolve the merge conflict?

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by Palakkgoyal** [comment]
I resolve the conflict. Can you please check.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
