### PR TITLE
Feature/login pages

### PR DESCRIPTION
**Pull request by sarkartanmay393**
### What have I done?
1. Removed Sign in and Signup Modals.
2. Add Auth Screens.

### CODE REVIEW

**Comment by narayan954** [comment]
Hi @sarkartanmay393 great progress. Can you make the default route to authentication, so I can secure the database rules, as currently they're open to access? thanks

**Comment by narayan954** [comment]
Also, google and facebook authentication won't work as you've not imported the providers .

**Comment by sarkartanmay393** [comment]
@narayan954 I've pointed out all of the topics, you mentioned. Look into it as soon as possible.

**Review by narayan954 — APPROVED** [review]
looks great to me!

**Comment by narayan954** [comment]
Thanks for the contribution!

**Pull request merged**
