### PR TITLE
added env file along with .env.sample file

### PR DESCRIPTION
**Pull request by 1010varun**

### CODE REVIEW

**Comment by 1010varun** [comment]
@narayan954 I have added .env file and mapped all its variables. I have also added a .env.sample file. Kindly review and merge my pr.

**Review by narayan954 — APPROVED** [review]
Looks good to me! and works in production as well!

**Comment by narayan954** [comment]
It worked perfectly! Thank you for your contribution!

**Comment by 1010varun** [comment]
@narayan954 can you kindly assign this under iwoc. It will be helpful.

**Pull request merged**
