### PR TITLE
Fix post alignment

### LINKED ISSUE #1084: Post alignment
### Description

The post in row mode are not aligned properly. I want to fix their alignment.

### Steps to reproduce

- Go to home page.
- Change to column mode.
- You will see some post that are not aligned properly.

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1084 
By fixing the height of image they are aligned properly.
Screenshot 2023-08-04 194617

### CODE REVIEW

**Comment by narayan954** [comment]
> This PR closes #1084 By fixing the height of image they are aligned properly. Screenshot 2023-08-04 194617

aren't they looking too big now,though? we can fix that later

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by Palakkgoyal** [comment]
> > This PR closes #1084 By fixing the height of image they are aligned properly. Screenshot 2023-08-04 194617
> 
> aren't they looking too big now,though? we can fix that later

Might be but images need atleast that much height. I think we can do the fixing with caption and header.

**Comment by narayan954** [comment]
> > > This PR closes #1084 By fixing the height of image they are aligned properly. Screenshot 2023-08-04 194617
> > 
> > 
> > aren't they looking too big now,though? we can fix that later
> 
> Might be but images need atleast that much height. I think we can do the fixing with caption and header.

right, there's too much whitespace above and below the image

**Pull request merged**
