### PR TITLE
added .env file

### PR DESCRIPTION
**Pull request by 1010varun**

### CODE REVIEW

**Comment by 1010varun** [comment]
@narayan954 kindly review and merge my pr under iwoc

**Review by narayan954 — CHANGES_REQUESTED** [review]
you just added .env to gitignore. How's that solving the issue?

**Comment by 1010varun** [comment]
Sir actually .env file is already made and all the key are already mentioned in it. If the issue is something else can you kindly explain it to me.

**Comment by narayan954** [comment]
> Sir actually .env file is already made and all the key are already mentioned in it. If the issue is something else can you kindly explain it to me.

Hi, the issue is that the script.js file is currently exposing the firebase API key and we want to secure it from open access. So we're creating a .env file but while creating .env file and accessing it, the application is crashing. You need to populate the env file with Api keys and remove it from open access so that no outsider can use our credentials of this application.
Hope you understand. :)

**Comment by narayan954** [comment]
You can read the conversation in that issue for more info

**Pull request closed without merging**
