### PR TITLE
Fixed Profile Page

### LINKED ISSUE #1297: Error when visiting someone's or my profile
### Description

There is an error thrown whenever I visit my or someone's profile.

### Steps to reproduce

Login in the dummygram website and then click on the menu near your profile pic and click on profile.. It throws an error and returns 404 not found page

### Screenshots

image

### Desktop (please complete the following information)

Windows 11.
Google Chrome

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I am a participant of a program
- [X] I want to work on this issue

### Optional information

_No response_

### PR DESCRIPTION
**Pull request by tushar-daiya**
Fixes #1297 
This issue was caused due to a change in character case of Friends to friends. The old accounts have an attribute Friends while the new one have friends with a small f. So when setting user data it was causing error to fetch newer accounts data.

Now the issue is fixed.

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for a spot on fix! Btw I just found, if we logout and login from different account, old account's data persists until we exit session or something. To confirm this, you can try to view your profile and you'd be redirected to the old login's username.

**Comment by tushar-daiya** [comment]
Yes I am also facing the issue. Can i try fixing that?

**Comment by narayan954** [comment]
> Yes I am also facing the issue. Can i try fixing that?

Sure, that'd be great! :)

**Pull request merged**
