### PR TITLE
Feature added to accept friend request

### LINKED ISSUE #953: [FEATURE] Accepting follow requests
### Description

Accepting follow requests is not yet implemented.
I would like to give it a shot.

### Screenshots

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #953 
I have added the feature to accept friend request.

### CODE REVIEW

**Comment by anamika7153** [comment]
@Palakkgoyal I wanted to clarify that while I did raise those issues, I hadn't yet had a chance to work on them myself. I understand that you saw the problems and wanted to help, which is commendable. However, I would appreciate it if, in the future, you could coordinate efforts before creating pull requests based on someone else's issues. It was very unprofessional of you to work on the issues before asking. 
In the future, could you please ask before creating pull requests for someone else's issues? Collaboration works best when we communicate and coordinate efforts.

**Comment by narayan954** [comment]
> @Palakkgoyal I wanted to clarify that while I did raise those issues, I hadn't yet had a chance to work on them myself. I understand that you saw the problems and wanted to help, which is commendable. However, I would appreciate it if, in the future, you could coordinate efforts before creating pull requests based on someone else's issues. It was very unprofessional of you to work on the issues before asking. How can you create PRs for other's issues without even asking? I checked that you have your own pending issues. You could have worked on them to get your PRs merged.

agreed!

**Review by narayan954 — APPROVED** [review]
lgtm

**Comment by Palakkgoyal** [comment]
> @Palakkgoyal I wanted to clarify that while I did raise those issues, I hadn't yet had a chance to work on them myself. I understand that you saw the problems and wanted to help, which is commendable. However, I would appreciate it if, in the future, you could coordinate efforts before creating pull requests based on someone else's issues. It was very unprofessional of you to work on the issues before asking. How can you create PRs for other's issues without even asking? I checked that you have your own pending issues. You could have worked on them to get your PRs merged.

Yes, I did a mistake to not `claim` the issue and I am sorry about that, as the issues that are 2 weeks or more older were stale and anyone could claim them whether they are mine and I only took those issues that were older than 2 weeks. You were creating so many issues and so so many were pending. This is also unprofessional to just create issues, get assigned and leave them. I don't mind if my issues are old, I am not working on them and just creating more and someone else take them. You also should have completed your assigned issues and create new. My only those issue are pending which I don't know how to fix.

**Pull request merged**
