### PR TITLE
Closes #182 [`Theme Mode`]

### LINKED ISSUE #182: Improve dark mode
### Description

Current implementation of dark mode is incorrect, it just inverts the color of some part of the page and not according to react. We can remove the vanilla implementation and provide a correct react implementation of the dark mode, which includes all parts of the page.

### Steps to reproduce

clicking on the dark mode toggle and checking the codebase shows this.

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sarkartanmay393**
### Light Mode: 
image

### Dark Mode:
image

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@narayan954 Review my PR

**Comment by narayan954** [comment]
> @narayan954 Review my PR

Hi @sarkartanmay393 you missed some elements like the text_input , can you please go through and confirm it and/or fix it. Also, please check for something else left on your side as well. I have my exams going on for another 1 day so I wont be available too long. Sorry for the inconvenience for one more day. 
issue182

Thank you

**Comment by sarkartanmay393** [comment]
@narayan954 you can review and merge, as soon as possible. JWOC P1 is ending soon.

**Comment by narayan954** [comment]
> @narayan954 you can review and merge, as soon as possible. JWOC P1 is ending soon.

okay tanmay, reviewing asap

**Comment by narayan954** [comment]
scroll to top button is no more at the center, can you look at it @sarkartanmay393 , else it's okay

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
Thanks for your contribution!!

**Pull request merged**
