### PR TITLE
Update readme file

### PR DESCRIPTION
**Pull request by Suryansh1720001**
Hey @narayan954 
This PR is raised under issue #183 

## Features that I added -
- Project admin details
- Add the contributing line with a guideline link so that everyone motivates by that.
- Center heading for more attractive
- adding the footer part in the readme file

Kindly check this and merge it accordingly.

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by narayan954** [comment]
thanks for your contributions!

**Comment by Suryansh1720001** [comment]
@narayan954 
By mistake you forgot to add the medium label, I guess. 
Kindly add that so that this repo consider under IWOC with some difficulty level.

**Comment by narayan954** [comment]
> @narayan954 By mistake you forgot to add the medium label, I guess. Kindly add that so that this repo consider under IWOC with some difficulty level.

yeah sure,  thanks for the reminder.

**Pull request merged**
