### PR TITLE
changes made in eye icon

### LINKED ISSUE #907: Regarding the styling of eye icon in the password field
### Description

the eye icon field is not going well with the entire theme in the dark  mode.
I would like to make some changes to make it look better

### Steps to reproduce

I will change the css of the page

### Screenshots

image

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by shruuti321**
Closes #907 
I have restyled the eye icon by changing background color,icon color and increasing icon size in both login and signup pages.
Kindly review and merge
image
image

### CODE REVIEW

**Comment by shruuti321** [comment]
@narayan954 please review the pr

**Comment by narayan954** [comment]
> Closes #907 I have restyled the eye icon by changing background color,icon color and increasing icon size in both login and signup pages. Kindly review and merge image image

Hi @shruuti321 thanks for enhancing it, but as you see in the third picture, it's not centered properly, can you try to fix that, please?

**Comment by shruuti321** [comment]
@narayan954 
Yes I tried several properties like margin-left:auto,margin-right:auto, text-align:center,align-items:center 
but nothing is working.
using display:flex got me this
image

but this has disturbed the alignment in signup page 
image
So kindly suggest whether to make this change or keep it as previous

**Comment by narayan954** [comment]
> @narayan954 Yes I tried several properties like margin-left:auto,margin-right:auto, text-align:center,align-items:center but nothing is working. using display:flex got me this image
> 
> but this has disturbed the alignment in signup page image So kindly suggest whether to make this change or keep it as previous

Does separating this css or  adding inline css just for this element work? If not, then it's alright, I'll allow this

**Comment by shruuti321** [comment]
> > @narayan954 Yes I tried several properties like margin-left:auto,margin-right:auto, text-align:center,align-items:center but nothing is working. using display:flex got me this image
> > but this has disturbed the alignment in signup page image So kindly suggest whether to make this change or keep it as previous
> 
> Does separating this css or adding inline css just for this element work? If not, then it's alright, I'll allow this

Not working, tried that as well

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by shruuti321** [comment]
@narayan954  may i know if you have approved the changes as proposed previously or the recent ones?
I havent created a pull request for the last change 

> > > @narayan954 Yes I tried several properties like margin-left:auto,margin-right:auto, text-align:center,align-items:center but nothing is working. using display:flex got me this image
> > > but this has disturbed the alignment in signup page image So kindly suggest whether to make this change or keep it as previous
> > 
> > 
> > Does separating this css or adding inline css just for this element work? If not, then it's alright, I'll allow this
> 
> Not working, tried that as well

May i know if you have approved the changes I have made earlier or the recent ones, because I haven't created a pull request for the recent changes yet

**Comment by narayan954** [comment]
> @narayan954  may i know if you have approved the changes as proposed previously or the recent ones?
> I havent created a pull request for the last change 
> 
> > > > @narayan954 Yes I tried several properties like margin-left:auto,margin-right:auto, text-align:center,align-items:center but nothing is working. using display:flex got me this image
> > > > but this has disturbed the alignment in signup page image So kindly suggest whether to make this change or keep it as previous
> > > 
> > > 
> > > Does separating this css or adding inline css just for this element work? If not, then it's alright, I'll allow this
> > 
> > Not working, tried that as well
> 
> May i know if you have approved the changes I have made earlier or the recent ones, because I haven't created a pull request for the recent changes yet

I went with the original changes.

Also fyi you don't need to create a new pull request if you want to add changes to this pr... you can directly commit and push and this pr will be updated with the commits automatically :)

**Comment by shruuti321** [comment]
> > @narayan954  may i know if you have approved the changes as proposed previously or the recent ones?
> > I havent created a pull request for the last change
> > > > > @narayan954 Yes I tried several properties like margin-left:auto,margin-right:auto, text-align:center,align-items:center but nothing is working. using display:flex got me this image
> > > > > but this has disturbed the alignment in signup page image So kindly suggest whether to make this change or keep it as previous
> > > > 
> > > > 
> > > > Does separating this css or adding inline css just for this element work? If not, then it's alright, I'll allow this
> > > 
> > > 
> > > Not working, tried that as well
> > 
> > 
> > May i know if you have approved the changes I have made earlier or the recent ones, because I haven't created a pull request for the recent changes yet
> 
> I went with the original changes.
> 
> Also fyi you don't need to create a new pull request if you want to add changes to this pr... you can directly commit and push and this pr will be updated with the commits automatically :)

Okay! Thanks a lot

**Pull request merged**
