### PR TITLE
Post liker list

### LINKED ISSUE #370: [FEATURE] Show post likers list
### Description

 Show post liker list on clicking likes quantity. 

### Screenshots

_No response_

### Additional information

It could be a modal with list of usernames who liked the post and clicking those username should open their profile(this is an already existing feature, just implement it here)

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #370 
I have added a new page to show post likes and it is responsive.
Screenshot 2023-07-26 125845

### CODE REVIEW

**Comment by narayan954** [comment]
> This PR closes issue no. #370 I have added a new page to show post likes and it is responsive. Screenshot 2023-07-26 125845

won't a modal look better @Palakkgoyal ? instead of separate page for likes?
Like this?
image

**Comment by narayan954** [comment]
Your approach is good, but I doubt if we really needed a separate page to show this small data?

**Comment by Palakkgoyal** [comment]
> > This PR closes issue no. #370 I have added a new page to show post likes and it is responsive. Screenshot 2023-07-26 125845
> 
> won't a modal look better @Palakkgoyal ? instead of separate page for likes? Like this? image

Yes, you are right I initially go for the modal but I faced some problems like on mobile if user click back to close the modal(instead of the close icon) then they get out of the website. But Okay, I will try that approach again and resolve the issues.

**Comment by narayan954** [comment]
> > > This PR closes issue no. #370 I have added a new page to show post likes and it is responsive. Screenshot 2023-07-26 125845
> > 
> > 
> > won't a modal look better @Palakkgoyal ? instead of separate page for likes? Like this? image
> 
> Yes, you are right I initially go for the modal but I faced some problems like on mobile if user click back to close the modal(instead of the close icon) then they get out of the website. But Okay, I will try that approach again and resolve the issues.

ohhh, I think Vijaylakshmi made the frontend  part for this, you can try to take help from her if you still face issue :)

**Comment by Palakkgoyal** [comment]
> > > > This PR closes issue no. #370 I have added a new page to show post likes and it is responsive. Screenshot 2023-07-26 125845
> > > 
> > > 
> > > won't a modal look better @Palakkgoyal ? instead of separate page for likes? Like this? image
> > 
> > 
> > Yes, you are right I initially go for the modal but I faced some problems like on mobile if user click back to close the modal(instead of the close icon) then they get out of the website. But Okay, I will try that approach again and resolve the issues.
> 
> ohhh, I think Vijaylakshmi made the frontend part for this, you can try to take help from her if you still face issue :)

Oh yes! she did hey @VijayalakshmiGanesh would you like to share about that?

**Comment by Palakkgoyal** [comment]
Hey, I did the required changes and also made it darkmode compatible.
Screenshot 2023-07-28 154521
Screenshot 2023-07-28 154554

**Comment by narayan954** [comment]
> Hey, I did the required changes and also made it darkmode compatible. Screenshot 2023-07-28 154521 Screenshot 2023-07-28 154554

awesome! merging it asap!

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @Palakkgoyal can you please add a bit more responsiveness? Else it's fine.
image

**Comment by Palakkgoyal** [comment]
Yes, sure.

**Comment by Palakkgoyal** [comment]
I have added some responsive. Can you please check and is there anything else I can do?

**Review by narayan954 — APPROVED** [review]
looks great to me!

**Pull request merged**
