### PR TITLE
Enhanced Add to favourite feature

### PR DESCRIPTION
**Pull request by shraddha761**
Issue reference #438

### CODE REVIEW

**Comment by shraddha761** [comment]
@narayan954 please review

**Comment by narayan954** [comment]
> @narayan954 please review

yes, reviewing it shortly

**Comment by narayan954** [comment]
> @narayan954 please review

I think you made some mistakes while solving merge conflicts. I'll be fixing them.

**Review by narayan954 — APPROVED** [review]
lgtm

**Pull request merged**
