### PR TITLE
Add save post option on post page

### LINKED ISSUE #1166: [FEATURE] Save post option on post page
### Description

There is no option to save post on post page which is really a problem. As if the user has a saved posts then, the only way to remove that post from saved is to find it in the home feed and nothing else. I want to add save and remove post feature there.

### Screenshots

Screenshot 2023-08-05 235903

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1166 
I have added the save post option on post page and, I removed the snackbar that appears when we save post or remove it. Cause, I think its a very small task and we don't need to show it.
If you want snackbar back, I can add it again.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
it looks great, but can you add the snackbar back as we're not indicating in any other way when the user saves a post. In any other social media, whenever we save posts we get a small indication, else we'd not be sure if post was saved, this affects a bit of UX, though it's not much good for Ui as you said.

**Comment by Palakkgoyal** [comment]
But, we are providing user indication that post is saved by making the post save button green and unsaved when it appears like other.

**Comment by narayan954** [comment]
> But, we are providing user indication that post is saved by making the post save button green and unsaved when it appears like other. Screenshot 2023-08-07 130948

that's a valid argument ;-; , alright it's fine

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
