### PR TITLE
Centralize

### LINKED ISSUE #1087: [FEATURE] Centralize user data
### Description

Every page of the website require current user data and every page fetch that seperately.
I want to make the fetch request from a single page and share it in the whole website. 

### Screenshots

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #1087 
I have centralize the user data and also fixed the aditya bug. It was not a that much big issue so I also refactored somewhat the login and signup page by taking out the OAuth function and making them more reusable and short.

### CODE REVIEW

**Comment by Palakkgoyal** [comment]
Hey @narayan954 Please try to merge my all PRs asap. Today is the last day. And I think leaderboard will only update once at 5PM

**Comment by narayan954** [comment]
> Hey @narayan954 Please try to merge my all PRs asap. Today is the last day. And I think leaderboard will only update once at 5PM

Hi @Palakkgoyal Actually us maintainers have time till tomorrow to merge, but I'll merge it by eve.... I'm currently outdoors.Will try to merge asap

**Comment by Palakkgoyal** [comment]
Oh Okay. Thanks for being so supportive.

**Comment by narayan954** [comment]
hi @Palakkgoyal can you please resolve conflicts? Thanks

**Comment by Palakkgoyal** [comment]
Resolved merge conflict.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
