### PR TITLE
Refactor the sign up and login page

### LINKED ISSUE #745: Refactor the sign up and login page
### Description

I will like to refactor the sign up and login page by breaking then into reuseable components

### Steps to reproduce

create a reuseable components

### Screenshots

_No response_

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Walexz01**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #745

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by narayan954** [comment]
hi can you please resolve the merge conflicts

**Comment by Walexz01** [comment]
Ok sir

**Comment by Walexz01** [comment]
@narayan954 have resolved the conflicts sir

**Comment by narayan954** [comment]
you didn't resolved it correctly, I'm reverting and resolving myself.

**Comment by narayan954** [comment]
There were several syntax errors, please make sure to test these small things out in future.

**Comment by Walexz01** [comment]
Ok sir

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
