### PR TITLE
added feature of forgot password

### PR DESCRIPTION
**Pull request by rudrakushwaha**

### CODE REVIEW

**Comment by rudrakushwaha** [comment]
@narayan954  added the forgot password feature please review it and suggest the changes if any.

**Comment by narayan954** [comment]
> @narayan954 added the forgot password feature please review it and suggest the changes if any.

Hello @rudrakushwaha , did you check/test how it looks?
UI is breaking due to some style changes you made in app.jsx, please fix them and check
image

**Review by narayan954 — CHANGES_REQUESTED** [review]
why are we installing a whole library just to get a toast component, whose alternative "snackbar" is already present/installed and in use in the same component. Please correct this and use snackbar if there's no actual need for toast component.

**Comment by narayan954** [comment]
is this done?

**Comment by rudrakushwaha** [comment]
Please give me some more time.

**Comment by narayan954** [comment]
> Please give me some more time.

it's alright take your time

**Comment by rudrakushwaha** [comment]
hello sir @narayan954  I have fixed the CSS and commited the changes. I have pushed it into the master branch but it is not displaying any new commit. And when I push it to addfeature branch I get this error.Please help

failed to push some refs to 'https://github.com/rudrakushwaha/dummygram.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by rudrakushwaha** [comment]
image

@narayan954  earliar addfeature branch is 21 commits behind now I have fetching and merging it is 5 commits ahead.

**Comment by narayan954** [comment]
> hello sir @narayan954 I have fixed the CSS and commited the changes. I have pushed it into the master branch but it is not displaying any new commit. And when I push it to addfeature branch I get this error.Please help
> 
> failed to push some refs to 'https://github.com/rudrakushwaha/dummygram.git' hint: Updates were rejected because the remote contains work that you do hint: not have locally. This is usually caused by another repository pushing hint: to the same ref. You may want to first integrate the remote changes hint: (e.g., 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Hi @rudrakushwaha , if you read the error, you'll find it says "Updates were rejected because the remote contains work that you do not have locally. This is usually caused by another repository pushing to the same ref. You may want to first integrate the remote changes (e.g., 'git pull ...') before pushing again. " 

In simple words, someone has pushed some changes as well to the branch you're trying to push on. So you'll first need to git pull, then git push. Git pull command is used here to update your branch with the remote. So please run git pull first and update your branch with remote. Also, to give your more hint, I had pushed a fix commit to your repository, so remote branch of yours runs ahead of your local branch and you'll need to update it with remote before making changes

**Comment by narayan954** [comment]
> image
> 
> @narayan954 earliar addfeature branch is 21 commits behind now I have fetching and merging it is 5 commits ahead.

it's alright, these 5 commits are your own commits, that you wish to add in my repo by creating this pull request

**Comment by rudrakushwaha** [comment]
Done sir @narayan954 Thank you so much. I have fixed the home page CSS you can check it and I have used toast feature of chakra UI as I am new to snackbar so I will have to go through it.

**Comment by narayan954** [comment]
> Done sir @narayan954 Thank you so much. I have fixed the home page CSS you can check it and I have used toast feature of chakra UI as I am new to snackbar so I will have to go through it.

snackbar is not much different, and it's already implemented, you just need to import and use there.... in fact it's present in that file as well, just copy the implementation

**Comment by rudrakushwaha** [comment]
okay @narayan954

**Comment by rudrakushwaha** [comment]
@narayan954  done. Now please check it I have removed the chakraUI

**Review by narayan954 — CHANGES_REQUESTED** [review]
looks good to me!

**Review by narayan954 — APPROVED** [review]

**Comment by rudrakushwaha** [comment]
Thank you sir @narayan954

**Pull request merged**
