### PR TITLE
Fix the issue while deleting the comments.

### PR DESCRIPTION
**Pull request by Jai-Marothiya**
Fix the issue in deleting the comments: Basically when we delete the comment every time the last comment is deleted because when we use closure during the map it always takes the comment value that is the last one and always the last element it passes to deleteComment() function. 

So I use one separate state that contains the id of a particular comment when it's deletion call.

### CODE REVIEW

**Comment by Jai-Marothiya** [comment]
Hi @narayan954,

Merge my pull request with the Hacktoberfest merge label.

Thanks.

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
> Fix the issue in deleting the comments: Basically when we delete the comment every time the last comment is deleted because when we use closure during the map it always takes the comment value that is the last one and always the last element it passes to deleteComment() function.
> 
> So I use one separate state that contains the id of a particular comment when it's deletion call.

that's a wonderful solution! thanks @Jai-Marothiya

**Comment by narayan954** [comment]
please remember to mention issue number in prs. it helps a lot!

**Pull request merged**
