### PR TITLE
delete button for favourite post is added [ Fixed #443 ]

### LINKED ISSUE #443: [FEATURE] Remove post from favourites
### What is the issue?
If I add some post as my favourites, there isn't any button that lets you to remove that post from the favourites

Screenshot 2023-06-06 210538

### Feature I want to implement
I want to implement some button. So, whenever I press that button that lets me remove the favourite post that I save earlier

### Additional information

I would like to work on this isuue assign it to me

### PR DESCRIPTION
**Pull request by AK4266**
### Added delete button that lets you to delete post that are added to the favourites

chrome_kvO62OxoTH

### CODE REVIEW

**Comment by AK4266** [comment]
Hey @narayan954  could you review my PR

**Comment by narayan954** [comment]
> Hey @narayan954 could you review my PR

yes sure, on it

**Comment by narayan954** [comment]
Hi @AK4266 , favourites list has been moved to a separate component and hence we also need to move there. 
Also, instead of adding a separate button, in the menu items of posts, add a menu item 'remove from favourites' which is to be accessible if the post is in favourites. Clicking on it removes it from favourites, both from homepage and favourite component

**Comment by AK4266** [comment]
@narayan954 All right, I will work on it

**Comment by AK4266** [comment]
@narayan954 Also we can do like, if the post is not  in the favourites then in the menu it shows add to favourites and if it is already in the favourites then it shows remove from favourites. What do you think??

**Comment by narayan954** [comment]
> @narayan954 Also we can do like, if the post is not in the favourites then in the menu it shows add to favourites and if it is already in the favourites then it shows remove from favourites. What do you think??

yes that works!

**Comment by narayan954** [comment]
closing this, you can open another pr

**Pull request closed without merging**
