### PR TITLE
Custom Scroll Bar

### PR DESCRIPTION
**Pull request by Devrajsinh03**
Issue no.: #93

I have added the custom scrollbar thumb.

tr

### CODE REVIEW

**Comment by Devrajsinh03** [comment]
@narayan954 I have added the custom scrollbar please check it out.

**Comment by narayan954** [comment]
Hi there @Devrajsinh03 thanks for the contribution, can you fix it for the dark mode too :) or do you think it is better that way?
image

**Comment by Devrajsinh03** [comment]
@narayan954 I will see to it in new issue but can you merge this PR for now?

**Comment by narayan954** [comment]
cool!

**Review by narayan954 — APPROVED** [review]
lgtm

**Pull request merged**
