### PR TITLE
Logo and fav icon updated

### PR DESCRIPTION
**Pull request by mohuxaiphasalik**
I have added a logo file to the asset folder and a fav icon file to the public folder 
in app.js I also imported the logo and set image src to the imported logo.

### CODE REVIEW

**Review by narayan954 — DISMISSED** [review]
The favicon looks great.

**Comment by narayan954** [comment]
@mohuxaiphasalik something's off with these changes , some syntax errors have emerged , can you please fix them ?

**Comment by mohuxaiphasalik** [comment]
Please send me screenshot of the error

**Comment by narayan954** [comment]
First I got the syntax error at line 221 of app.js , It was a quick fix , but then when starting the server , I am getting this error :(

image

**Comment by narayan954** [comment]
also, it's not properly styled
image

image

**Pull request closed without merging**
