### PR TITLE
Added like-color toggle feature

### PR DESCRIPTION
**Pull request by bhoopesh369**
Like button feature

### CODE REVIEW

**Comment by bhoopesh369** [comment]
@narayan954  hey i have included the features

**Comment by bhoopesh369** [comment]
Please accept the pr

**Review by narayan954 — APPROVED** [review]
lgtm

**Comment by narayan954** [comment]
Thanks for your contribution :)

**Comment by narayan954** [comment]
if you don't want the invalid label, ping me, I can remove that

**Pull request merged**
