### PR TITLE
Refactor codebase

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #494 
I have checked that each and every feature of the website is working as before.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
several things are missing in the changes, dates are not shown on posts, button on navbar is not in it's defined style, profile page is crashing and many more to check. Can you please fix that and recheck the stuffs? I feared it might happen, that's why I asked to implement refactoring in stages/parts.

**Comment by narayan954** [comment]
In my commit I've just formatted the code

**Comment by Palakkgoyal** [comment]
I think I should close this issue as I am not able to do it.

**Comment by narayan954** [comment]
> I think I should close this issue as I am not able to do it.

it's alright, you don't need to quit this early, I understand you worked really hard on this... I just checked and actually profile page is crashing on the production as well now due to one of the recent commits. I'll fix and merge this.

**Comment by Palakkgoyal** [comment]
> > I think I should close this issue as I am not able to do it.
> 
> it's alright, you don't need to quit this early, I understand you worked really hard on this... I just checked and actually profile page is crashing on the production as well now due to one of the recent commits, not yours. I'll fix and merge this.

Thanks a lot for understanding. You are really nice project admin.

**Comment by narayan954** [comment]
> > > I think I should close this issue as I am not able to do it.
> > 
> > 
> > it's alright, you don't need to quit this early, I understand you worked really hard on this... I just checked and actually profile page is crashing on the production as well now due to one of the recent commits, not yours. I'll fix and merge this.
> 
> Thanks a lot for understanding. You are really nice project admin.

Thank you :)

**Review by narayan954 — APPROVED** [review]
lgtm!

**Pull request merged**
