### PR TITLE
Implement footer in sidebar

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #542 
A simple footer for sidebar. 
I was not able to think of anything else to put. I think you should take a MIT license for dummygram. If you want you can make this issue of level 1

### CODE REVIEW

**Comment by narayan954** [comment]
> This PR closes issue no. #542 A simple footer for sidebar. I was not able to think of anything else to put. I think you should take a MIT license for dummygram. If you want you can make this issue of level 1

there's already MIT license for Dummygram

**Comment by narayan954** [comment]
Hi @Palakkgoyal , after updating the pull request to the current version of master, css is breaking, can you try to fix that... 
Ps: some classes are conflicting after the code refactoring we performed

**Comment by Palakkgoyal** [comment]
Ohk sure. I will fix that.

**Comment by Palakkgoyal** [comment]
I have resolved the bug. Please check.

**Comment by narayan954** [comment]
> I have resolved the bug. Please check.

Sure!

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Pull request merged**
