### PR TITLE
image displayed immediately after selecting the image and after updating it

### PR DESCRIPTION
**Pull request by anamika7153**
Closes: #604 

## Video

https://github.com/narayan954/dummygram/assets/66116440/8622f769-a885-4cd4-9612-5a76b5b1cbd1

### CODE REVIEW

**Comment by narayan954** [comment]
This is still a work in progress right?

**Comment by narayan954** [comment]
there's a little bug in this, once we update the pic, if we try to update again, the img wont change this time

**Comment by anamika7153** [comment]
> This is still a work in progress right?

yes

**Comment by anamika7153** [comment]
> there's a little bug in this, once we update the pic, if we try to update again, the img wont change this time on the display, but will work in the backend and get updated

I have checked and the image is changing second time also but I marked it as draft because the profile pic is not updating in the post header.

**Comment by narayan954** [comment]
> > there's a little bug in this, once we update the pic, if we try to update again, the img wont change this time on the display, but will work in the backend and get updated
> 
> I have checked and the image is changing second time also but I marked it as draft because the profile pic is not updating in the post header.

actually post header is a different issue. To summarise, when creating a post, user details like picture,email etc data are saved in the posts collection as well. So to fix this we need to update the create post component and instead of attaching all of these details we should just add the uid or username. So when we load the post feed, post's meta shall be generated dynamically.

**Comment by narayan954** [comment]
> > > there's a little bug in this, once we update the pic, if we try to update again, the img wont change this time on the display, but will work in the backend and get updated
> > 
> > 
> > I have checked and the image is changing second time also but I marked it as draft because the profile pic is not updating in the post header.
> 
> actually post header is a different issue. To summarise, when creating a post, user details like picture,email etc data are saved in the posts collection as well. So to fix this we need to update the create post component and instead of attaching all of these details we should just add the uid or username. So when we load the post feed, post's meta shall be generated dynamically.

this is because earlier there was no user collection.

**Comment by anamika7153** [comment]
@narayan954  you may close this as the issue has been resolved by #908

**Pull request closed without merging**
