### PR TITLE
Changed the alignment of scrollTop button

### PR DESCRIPTION
**Pull request by souravrjpt**
Changed the alignment and position of the scroll Top button in index.css file.

### CODE REVIEW

**Comment by narayan954** [comment]
> Changed the alignment and position of the scroll Top button in index.css file.

provide screenshots

**Review by narayan954 — CHANGES_REQUESTED** [review]
test/format your code. Also, Why's that located at left corner, it's not good for UX
The other buttons style have also been altered as it can be seen
image

**Comment by narayan954** [comment]
Add this button at the bottom of the sidebar

**Comment by souravrjpt** [comment]
> Add this button at the bottom of the sidebar

OK, I'll do it as soon as my tests gets over.

**Comment by narayan954** [comment]
closing this, you can open another pr

**Pull request closed without merging**
