### PR TITLE
Solved the responsiveness for all devices #306

### PR DESCRIPTION
**Pull request by crocmons**
Solved the issue of responsiveness for all devices #306

dummygram2
dummygram1

### CODE REVIEW

**Comment by crocmons** [comment]
> 

yes , I can ..you want the profile icon should be next to the new post right?

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by narayan954** [comment]
Thanks for your contribution! :)

**Comment by narayan954** [comment]
upgraded the level

**Comment by crocmons** [comment]
> upgraded the level

thank you!😃

**Pull request merged**
