### PR TITLE
css changes to submenu of navbar

### PR DESCRIPTION
**Pull request by mahekkg**
Changed styles of the submenu of navbar which works with both light and dark mode. Also made changes in the alignment.

Screenshot (392)

### CODE REVIEW

**Review by AK4266 — COMMENTED** [review]
LGTM!

**Comment by narayan954** [comment]
> LGTM!

thanks for reviewing! :)

**Comment by AK4266** [comment]
@narayan954 No prob, happy to help

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by narayan954** [comment]
@mahekkg please mention the issue number so I can add the proper tags and close issue

**Comment by mahekkg** [comment]
@narayan954 its #278

**Comment by narayan954** [comment]
Thanks for your contribution Mahek!

**Pull request merged**
