### PR TITLE
applied like color-toggle again

### PR DESCRIPTION
**Pull request by narayan954**
production was failing without any reason so reverted and pushing again

### CODE REVIEW

**Comment by narayan954** [comment]
@bhoopesh369 we're getting these errors in the build.
image

Maybe due to older posts not having this property is what's causing the problem.

**Comment by narayan954** [comment]
you may work on the development branch of this project, which is already having these changes and try to fix the issue, if before me.

**Comment by narayan954** [comment]
try running the build script and check that production build

**Comment by bhoopesh369** [comment]
Heyy @narayan954 
I have solved the issue 
now you can merge the pull request

**Comment by bhoopesh369** [comment]
> Heyy @narayan954 I have solved the issue now you can merge the pull request

I have made a new PR... check it out

**Comment by narayan954** [comment]
> > Heyy @narayan954 I have solved the issue now you can merge the pull request
> 
> I have made a new PR... check it out

checked and merged

**Review by narayan954 — COMMENTED** [review]
fixed warnings and formatted code

**Pull request merged**
