### PR TITLE
Edit profile

### LINKED ISSUE #313: [FEATURE] Changes in Profile and Create Post tab.
### Description

I think the User Profile page can be improved as far as UI is concerned. There should be an option for editing the username of the user in the User Profile page. Also, all the posts made by the user should be shown up in the Profile page.

For create post, I think a different route should be created for this purpose. Previewing the image before posting is also a good option for its improvement.

@narayan954 kindly assign this issue to me under GSSOC'23. I am pretty sure that I could work on them efficiently.

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #313 
In this I have created a new component that let the user edit their whole profile and I have also added some extra fields such as bio and country. It also shows preview of image so that it become easy for user to select and user do not need to reload the page for checking the changes.
Screenshot (621)

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
checking........

**Review by narayan954 — APPROVED** [review]
looks good to me!

**Comment by narayan954** [comment]
I'm not sure, if this should be level 2 or 3 ;-;

**Comment by Palakkgoyal** [comment]
I think it should be level3 cause adding a bio feature only is level2 and previewing image is also level2. Apart from that I added an extra field of location and also made all of them editable.
What is your views on it @narayan954 ?

**Comment by narayan954** [comment]
> I think it should be level3 cause adding a bio feature only is level2 and previewing image is also level2. Apart from that I added an extra field of location and also made all of them editable.
> What is your views on it @narayan954 ?

fair enough :)

**Pull request merged**
