### PR TITLE
Fixes #133 [`Cypress`]

### LINKED ISSUE #133: Adding Unit Test Cases for  React Project
### Description

Can I work on this Project?
I can add unit test scripts using jest in this Project.
Please allow me to continue with the same.
About Unit Testing :
Unit Testing is used to check whether the Input fields are working correctly without interaction of any Human.
Here I write a unit tests using Jest which is auto-installed which creating react app.

So I will write a test for each component and the good thing is the code is used for testing only while deploying app it doesn't effect the perfornce but it is useful to test our react app without human intraction.

Hoping to hear from you soon !!

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by sarkartanmay393**
**Dummygram** is not well structured from scratch and that's why I ain't sure about its scalability. 
I've added basic test cases that check whether **dummygram** works or not.

https://user-images.githubusercontent.com/84321236/222804606-5cbd421f-7ec9-4f7b-99ae-f09d60f70bfe.mov

### CODE REVIEW

**Comment by sarkartanmay393** [comment]
@narayan954 You can give it a look, and if you like to perform tests by yourself, you can just `npm i` and `npx cypress open`, and the rest can be found in their docs.

**Comment by narayan954** [comment]
> @narayan954 You can give it a look, and if you like to perform tests by yourself, you can just `npm i` and `npx cypress open`, and the rest can be found in their docs.

yeah, thanks, I was just going to test it out

**Review by narayan954 — APPROVED** [review]
lgtm!

**Comment by narayan954** [comment]
Thanks for your contribution! We can add more test cases later and by the way, would you like to work on adding steps(documentation) for how to use cypress in this project for testing in a separate issue? If interested, you can work on this! else it's fine

**Comment by sarkartanmay393** [comment]
> Thanks for your contribution! We can add more test cases later by the way, would you like to work on adding steps(documentation) for how to use cypress in this project for testing in a separate issue? If interested, you can work on this! else it's fine

@narayan954 
I would love to help with that. We can discuss it on Discord.
Discord Username: **TANMAY#6159**

**Comment by narayan954** [comment]
> > Thanks for your contribution! We can add more test cases later by the way, would you like to work on adding steps(documentation) for how to use cypress in this project for testing in a separate issue? If interested, you can work on this! else it's fine
> 
> @narayan954 I would love to help with that. We can discuss it on Discord. Discord Username: **TANMAY#6159**

got it!

**Pull request merged**
