### PR TITLE
Creat a new UI for profile page

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes issue no. #782 
I have created a new UI for profile page and added some new fields as static such as profile background image, location and bio.
I have also checked its responsiveness and it works fine.

### CODE REVIEW

**Review by narayan954 — CHANGES_REQUESTED** [review]
Hi @Palakkgoyal save button for editting picture seems to be disoriented, can you please look into it?
image
Also, email address is not shown, would that be okay? And current users without a username would have blank as username,that's fine for now. Also also also, I logged in using oauth but I perhaps didn't get the default username as you had implemented in the earlier feature, or this page was unable to fetch it for profile page. Can you check that?

By the way, this seems like a great implementation as we can progressively enable bio feature/cover picture feature and many other. Thanks

**Comment by narayan954** [comment]
> Hi @Palakkgoyal save button for editting picture seems to be disoriented, can you please look into it? image Also, email address is not shown, would that be okay? And current users without a username would have blank as username,that's fine for now. Also also also, I logged in using oauth but I perhaps didn't get the default username as you had implemented in the earlier feature, or this page was unable to fetch it for profile page. Can you check that?
> 
> By the way, this seems like a great implementation as we can progressively enable bio feature/cover picture feature and many other. Thanks

about the uid/username, it gets lost on refreshing the page

**Comment by Palakkgoyal** [comment]
Yes, I will check all the issues. I think we should not display email on the profile page rather we can further make it like when we click on the edit icon it will open a dialog box which will contain all the user info and user can edit everything at once there.

**Comment by narayan954** [comment]
> Yes, I will check all the issues. I think we should not display email on the profile page rather we can further make it like when we click on the edit icon it will open a dialog box which will contain all the user info and user can edit everything at once there.

right, I agree!

**Comment by Palakkgoyal** [comment]
Have you merged that PR that was related to profile page?

**Comment by narayan954** [comment]
> Have you merged that PR that was related to profile page?

Yes, right now!

**Comment by Palakkgoyal** [comment]
Ohk. Got that.

**Pull request closed without merging**
