### PR TITLE
Search user

### LINKED ISSUE #755: [BUG]: Search operation is case sensitive and inefficient
### Description

- Searching is case-sensitive. 
- Also it's not working efficiently, it's not providing search result .
- Also it should provide clear information as to what it searches (user or some post). There should be a heading like "Search users".

### Steps to reproduce

Go to website and search users

## Case sensitive issue:

|     |                   |
|-----|---------------------------------|
| **There is a user: "viju g"** |  |
|  **When i write "vij" (in lowercase), it gives result:** |  |
| **When i write "Vij" (in upper-case), it doesn't give result** |  |

## Inefficiency:

|     |                   |
|-----|---------------------------------|
| **There are users "Narayan" and "Tisha Garg"** |  |
|  **When I search for them , doesn't give results:** |  |
|  |  |

### Desktop (please complete the following information)

_No response_

### Smartphone (please complete the following information)

_No response_

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### LINKED ISSUE #941: [FEATURE] Adding a grid view on profile
### Description

I want to add a grid view on profile page for feed like instagram. 

### Screenshots

Screenshot (623)

### Additional information

_No response_

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I have checked the existing issues
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Palakkgoyal**
This PR closes #755 
I have added a search user functionality with a debounced function so that search will only happen after 2s of user stop typing to decrease fetch requests. The search will fetch 7 users at a time. If someone click on the user li they will be navigated to that user profile.

### CODE REVIEW

**Review by narayan954 — APPROVED** [review]
looks awesome to me!

**Review by narayan954 — APPROVED** [review]
This looks awesome to me, but I think you've mistakenly solved #755 instead instead of moving it to navbar XD

**Comment by Palakkgoyal** [comment]
Yes, might be cause I was confused as we were querying for user but that will not suit in the navbar and in our discussion you mentioned that it might need some different logic. I thought you are saying about fetching data😅. So, I did that changes. 
Sorry @anamika7153 for mistakenly taking your assigned issue.

**Comment by narayan954** [comment]
> Yes, might be cause I was confused as we were querying for user but that will not suit in the navbar and in our discussion you mentioned that it might need some different logic. I thought you are saying about fetching datasweat_smile. So, I did that changes. Sorry @anamika7153 for mistakenly taking your assigned issue.

Yes, it's alright! Btw still query is behaving unwell because some users have name field and some have displayname field... thinking to modify all of them to displayname

**Comment by narayan954** [comment]
> > Yes, might be cause I was confused as we were querying for user but that will not suit in the navbar and in our discussion you mentioned that it might need some different logic. I thought you are saying about fetching datasweat_smile. So, I did that changes. Sorry @anamika7153 for mistakenly taking your assigned issue.
> 
> Yes, it's alright! Btw still query is behaving unwell because some users have name field and some have displayname field and query is only searching on name field... thinking to modify all of them to displayname

and I am giving that moving issu to @anamika7153 actually, maybe I think we can add a search icon or something on navbar nah?

**Comment by Palakkgoyal** [comment]
> > Yes, might be cause I was confused as we were querying for user but that will not suit in the navbar and in our discussion you mentioned that it might need some different logic. I thought you are saying about fetching datasweat_smile. So, I did that changes. Sorry @anamika7153 for mistakenly taking your assigned issue.
> 
> Yes, it's alright! Btw still query is behaving unwell because some users have name field and some have displayname field and query is only searching on name field... thinking to modify all of them to displayname

Yes, that was a problem for me as well. So, I picked the name field. Moving to completely one field would be a good choice.

**Comment by Palakkgoyal** [comment]
> > > Yes, might be cause I was confused as we were querying for user but that will not suit in the navbar and in our discussion you mentioned that it might need some different logic. I thought you are saying about fetching datasweat_smile. So, I did that changes. Sorry @anamika7153 for mistakenly taking your assigned issue.
> > 
> > 
> > Yes, it's alright! Btw still query is behaving unwell because some users have name field and some have displayname field and query is only searching on name field... thinking to modify all of them to displayname
> 
> and I am giving that moving issu to @anamika7153 actually, maybe I think we can add a search icon or something on navbar nah?

Yes, I think we should just add a icon to navbar. But, what will happen on the mobile view. As there will be two icon one on navbar and one on the below bar.

**Comment by narayan954** [comment]
sidebar search is going to be eliminated actually

**Comment by narayan954** [comment]
> > > > Yes, might be cause I was confused as we were querying for user but that will not suit in the navbar and in our discussion you mentioned that it might need some different logic. I thought you are saying about fetching datasweat_smile. So, I did that changes. Sorry @anamika7153 for mistakenly taking your assigned issue.
> > > 
> > > 
> > > Yes, it's alright! Btw still query is behaving unwell because some users have name field and some have displayname field and query is only searching on name field... thinking to modify all of them to displayname
> > 
> > 
> > and I am giving that moving issu to @anamika7153 actually, maybe I think we can add a search icon or something on navbar nah?
> 
> Yes, I think we should just add a icon to navbar. But, what will happen on the mobile view. As there will be two icon one on navbar and one on the below bar.

done lol!

**Pull request merged**
